### ISSUE TITLE
attitude_control assumes GPS

### ISSUE THREAD

**Issue by acdriec** [dji-sdk/Onboard-SDK-ROS#10]
Hi, 

I noticed that when we want to use drone->attitude_control(0x40, x, x, x, x); (both horizontal and vertical velocity) that we need GPS. (Test: works outdoor with GPS but not indoor without GPS). Is there a possibility to use it without GPS ? Or another way to send pitch, roll speeds to the matrice ?

Kind Regards,
Dries

**Comment by acdriec** [comment]
This is in branch 2.3, I see that you can use the virtual RC channels in 3.1 does this work without GPS. And is there a way to do it in branch 2.3 without GPS ?

**Comment by lanyusea** [comment]
yes, you can control the roll/pitch angle directly without GPS.
if you want to use the velocity/position control mode, GPS signal is
necessary.

**Comment by acdriec** [comment]
You mean in HORI_ATTI_TILT_ANG mode ?

**Comment by lanyusea** [comment]
yes

**Comment by acdriec** [comment]
Ok we will test this very soon, thanks !

**Comment by lanyusea** [comment]
but BE CAREFUL!

the drone cannot stable itself when in this mode.

**Comment by acdriec** [comment]
Works like a charm !

**Comment by jasperza** [comment]
If we are indoors with no GPS but have guidance in opti mode, what method should we use to control the drone?

**Comment by lanyusea** [comment]
@jasperza I recommend the velocity control
