### ISSUE TITLE
Firmware release date for M600 compatible with v3.3 of the Onboard-SDK

### ISSUE THREAD

**Issue by asiron** [dji-sdk/Onboard-SDK-ROS#100]
When are you planning on releasing the necessary firmware in order to use the new 3.3 version of the ROS-SDK with M600?

Cheers,
Maciej

**Comment by rohitsantdji** [comment]
The docs have been updated on the website - the [versioning page](http://developer.dji.com/onboard-sdk/documentation/appendix/versioning.html) now reflects the projected end-july release date.

**Comment by rohitsantdji** [comment]
Duplicate of dji-sdk/Onboard-SDK#141 and dji-sdk/Onboard-SDK#137

**Comment by rohitsantdji** [comment]
@asiron M600 firmware with support for OSDK 3.3.1 has been released today.
