### ISSUE TITLE
Vertical velocity control does not work

### ISSUE THREAD

**Issue by acdriec** [dji-sdk/Onboard-SDK-ROS#101]
I want to control the N3 in vertical velocity mode as in : 

```
sensor_msgs::Joy controlPosYaw;
    uint8_t flag = (DJISDK::VERTICAL_VELOCITY   |
                    DJISDK::HORIZONTAL_VELOCITY |
                    DJISDK::YAW_RATE            |
                    DJISDK::HORIZONTAL_BODY  |
                    DJISDK::STABLE_ENABLE);

    controlPosYaw.axes.push_back(0);//x
    controlPosYaw.axes.push_back(0);//y
    controlPosYaw.axes.push_back(3);//z
    controlPosYaw.axes.push_back(0);//yawrad
    controlPosYaw.axes.push_back(flag);
    ctrlPosYawPub.publish(controlPosYaw);
```

But the N3 reacts as in POSITION mode, so it go to an altitude of 3meter. 

Is this a bug or normal ?

Kind regards

**UPDATE:

Ok found it, you should publish to "dji_sdk/flight_control_setpoint_generic" for velocity !**

**Comment by rohitsantdji** [comment]
Good to know you resolved the issue! Alternatively, in your case, you can also publish to `/dji_sdk/flight_control_setpoint_ENUvelocity_yawrate` as mentioned in the [wiki](http://wiki.ros.org/dji_sdk)
