### ISSUE TITLE
Ronin-MX has corrupted output from /dji_sdk/gimbal

### ISSUE THREAD

**Issue by asiron** [dji-sdk/Onboard-SDK-ROS#103]
We are using M600 with the Ronin-MX gimbal and the output of `/dji_sdk/gimbal` topic is corrupted as the Onboard SDK OPEN protocol describes :

**"Note: Rotating 90 degree in pitch direction will cause gimbal lock problem, in which the value of roll and yaw are not reliable."**

This makes us unable to fly and point the camera downwards as the value of yaw and roll is not reliable. It is very important for us to always have a reliable reading from the gimbal in order to transform into the camera frame. Furthermore, once we pass the -90 degree value, it does not continue to -180 degrees, but starts increasing to 0 degrees again.

Are you planning on fixing it?

**Comment by asiron** [comment]
I actually haven't check if the same issue appears in the Zenmuse X3 gimbal. I will check it tomorrow and update the issue

**Comment by asiron** [comment]
This issue does not appear with the Zenmuse X3 gimbal

**Comment by zliDJI** [comment]
Hi, asiron, thanks for your feedback and your effort to test over multiple gimbals. We will test the issue on our side later.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
