### ISSUE TITLE
Zenmuse X3 and Ronin-MX gimbals have different frames

### ISSUE THREAD

**Issue by asiron** [dji-sdk/Onboard-SDK-ROS#104]
As described in #39, the output of `/dji_sdk/gimbal` using the Zenmuse X3 gimbal is given in NED frame. However, the output of the same topic, while using the Ronin-MX is in the body-frame.

It would be worthwhile to make sure, that both of them are using the same coordinate frame.

**Comment by rohitsantdji** [comment]
Thanks for doing this investigation! We will try to make this happen.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
