### ISSUE TITLE
Supported DJI drones with ROS-SDK

### ISSUE THREAD

**Issue by aduttaUNF** [dji-sdk/Onboard-SDK-ROS#105]
I am planning to buy Phantom 3 standard edition for academic research. Will it be possible to control the drone and get data from it through ROS?

**Comment by zliDJI** [comment]
Hi, for a list of supported devices by onboard sdk, here is the [link](https://developer.dji.com/onboard-sdk/documentation/introduction/osdk-hardware-introduction.html#supported-products).

If you have to buy Phantom 3 and want to do some programming, you can try the Mobile SDK, which supports[ most of DJI's products](https://developer.dji.com/mobile-sdk/documentation/introduction/product_introduction.html#supported-products).
