### ISSUE TITLE
Disable RC Stick Control when in F-Mode

### ISSUE THREAD

**Issue by fong7x7** [dji-sdk/Onboard-SDK-ROS#107]
I'm trying to disable the stick controls when the controller is switched into F-Mode.  This is so the pilot can't interfere with the commands given by the onboard sdk.  The pilot can then switch out of F-Mode to regain control. Is there a way to disable the stick controls this way using the through the ROS node or directly with the onboard sdk?

**Comment by rohitsantdji** [comment]
The RC commands are automatically **rejected** by the drone when the OSDK is executing movement control commands, but in all other scenarios RC commands enjoy a higher priority and will be accepted. During GPS missions (waypoint, hotpoint) the sticks are used to control the yaw and speed, for example, and cannot be turned off.
