### ISSUE TITLE
Zenmuse Z3 onboard/ROS SDK focus control

### ISSUE THREAD

**Issue by giovannidurso** [dji-sdk/Onboard-SDK-ROS#111]
Hi,

Is it possible to control the focus for a Z3 camera with the Onboard or ROS SDK? 
It says in the onboard SDK documentation "DJI cameras with variable focus allow both manual and automatic focusing. When in automatic mode, the camera will calculate focus from an area in the image, which can be set through the SDK.", but I am unable to locate the particular command to achieve this.

I have only been able to find the ability to control focus for a X5 using the Android SDK

Thanks

**Comment by rohitsantdji** [comment]
Hi Giovanni - we apologize for the misleading documentation adapted from the DJI Mobile SDK. You can only control the focus through the Android /iOS SDKs.
