### ISSUE TITLE
Where can I download OSDK-ROS 3.2 ?

### ISSUE THREAD

**Issue by varishearth** [dji-sdk/Onboard-SDK-ROS#113]
As the title, I use M100 to develop app, but the satisfied version is 3.2, the old version in this site https://github.com/dji-sdk/Onboard-SDK-ROS/releases is OSDK, not ROS. So where can I download OSDK-ROS 3.2?

Thank you!

**Comment by andre-nguyen** [comment]
https://github.com/dji-sdk/Onboard-SDK-ROS/tree/3.2

**Comment by varishearth** [comment]
Thank you very much!

**Comment by rohitsantdji** [comment]
OSDK 3.3.1 was released yesterday, bringing backwards compatibility for M100. Check it out!
