### ISSUE TITLE
SDKInfo feedback disappeared in 3.3

### ISSUE THREAD

**Issue by edkoch** [dji-sdk/Onboard-SDK-ROS#115]
Maybe I'm missing something, but I noticed that device status (i.e. SDKInfo) disappeared in 3.3. It is a valuable piece of feedback that is use to determine who has control of the FCU. I went ahead and added a simple std::Uint8 topic to dji_sdk_node_publisher.cpp in the 50Hz section and confirmed that it works as expected. See the code snippet below. My question is whether you guys intend to add back in the whole SDKInfo feedback in a future release or should I go ahead and submit a pull request for what I did. Note that for my purposes I am only feeding back the deviceStatus and not the other fields in SDKInfo.

  //update device control info
  if (data_enable_flag & DataBroadcast::DATA_ENABLE_FLAG::A3_HAS_DEVICE)
  {
    std_msgs::UInt8 status_device;
    status_device.data = vehicle->broadcast->getSDKInfo().deviceStatus;
    p->device_status_publisher.publish(status_device);
  }

**Comment by edkoch** [comment]
BTW given that there is bug in the return value of the SDK Authority service it is impossible to know if you got authority or not without this feedback. I have been able to confirm that even though the SDK Authority service returns false the SDK still gets authority as evidenced by the deviceStatus being set to 2.

**Comment by rohitsantdji** [comment]
Hi @edkoch ! In the 3.3.1 release, we've fixed the control authority service bug. Could you give it a shot?

**Comment by amenonDJI** [comment]
@edkoch Have you had a chance to test this out?

**Comment by edkoch** [comment]
Yes I did and it seems to work.


thanks,

-ed koch

**Comment by amenonDJI** [comment]
Great thanks. Closing this issue.
