### ISSUE TITLE
SDK compiling issue with RPi3 (Ubuntu Mate 16.04 with ROS Kinetic)

### ISSUE THREAD

**Issue by rocklinsuv** [dji-sdk/Onboard-SDK-ROS#116]
Hi there,

Recently I've experienced an issue when compiling the Onboard-SDK-ROS package. I'm currently using a Raspberry Pi 3 with Ubuntu Mate 16.04 and ROS Kinetic installed. First I downloaded Onboard-SDK and compiled it without any issue. However, when I tried to catkin_make the Onboard-SDK-ROS package, it stuck at 90% every time and the system froze. Here are some screen shoots I've captured:

I tried Onboard-SDK v3.2 with Onboard-SDK-ROS v3.2:
![3 2](https://user-images.githubusercontent.com/7424627/28996802-5833e01a-7a39-11e7-8377-f4e7eb77874b.jpg)

Onboard-SDK v3.3 with Onboard-SDK-ROS v3.3
![3 3](https://user-images.githubusercontent.com/7424627/28996809-67922d6e-7a39-11e7-9a6c-a99a5a7a3c7b.jpg) 

Even the newest Onboard-SDK v3.3.1 with Onboard-SDK-ROS v3.3.1
![3 3 1](https://user-images.githubusercontent.com/7424627/28996811-70d2058e-7a39-11e7-81b0-1b5676b9e637.jpg) 

It seems like the dji-sdk-node would not compile. I previously tried to compile everything in a Virtual Machine with Ubuntu 16.04 and ROS Kinetic without any issue. Any thoughts that may help me resolve this problem? Many thanks!

Cheers,

**Comment by andre-nguyen** [comment]
On memory limited systems you can try to compile with only one job. e.g.
```
catkin_make -j1
```

**Comment by rocklinsuv** [comment]
Woaw! It worked like a charm! Many thanks mate :smiley:
