### ISSUE TITLE
ERROR/1 @ functionalSetUp, L182: Hardware Sync not supported!

### ISSUE THREAD

**Issue by tash-rif** [dji-sdk/Onboard-SDK-ROS#117]
Hi,

I have a matrice 100 and just tried out the 3.3.1 release. When launching sdk.launch, i noticed the following line.

`ERROR/1 @ functionalSetUp, L182: Hardware Sync not supported!`

I saw the online documentation on: https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-hardware-sync.html

and it says 

> NOTE: Hardware Sync feature not supported in Matrice 100.

Is this a temporary missing feature that could be provided in a future release or the m100/N1 controller is not capable of providing Hardware Sync feature. How crucial is this feature when running external fusion algorithms?

Thank you.

**Comment by rohitsantdji** [comment]
The M100/N1 controller is unfortunately not able to support this functionality, so it will not be possible to introduce the hardware sync feature later. 

We do provide a software sync stamping mechanism which can be used for loosely time-aligning the data from the M100 to your external sensors. If you want to do high-rate fusion with the onboard IMU that will be harder to do without hardware sync.
