### ISSUE TITLE
Local Position missing in SDK 3.3

### ISSUE THREAD

**Issue by prodrone-dev** [dji-sdk/Onboard-SDK-ROS#121]
Dear @amenonDJI,

writing you on behalf of [ProDrone](http://pro-drone.eu/) development team. We have developed autonomous system for wind turbine's blade inspection, which support your API thus can be installed on DJI system. We have already several clients operating worldwide, likewise using DJI drones as their flying platform.

We are moving our system from DJI Onboard SDK ROS 3.2 to 3.3,  and we noticed the Local Position information is not available as a published topic anymore -- I'm using [dji sdk ros wiki](http://wiki.ros.org/dji_sdk) as reference. We think the decision to remove it wasn't thought through enough - most of the developers are using this information as primary to determine the UAV position in space. And with SDK 3.3. this is no longer available and would require additional steps to convert it from GPS data. It would also simplify the transition to the new version of SDK.

Would it be possible to integrate information about the Local Pose in the API as a new minor release of the SDK? 
What would eventually be the ETA for the deployment of the feature?

Kind Regards,
ProDrone

**Comment by amenonDJI** [comment]
@prodrone-dev Apologize for not including this feature in the 3.3 release. We do plan to release Local Position Control as a part of our next release that will happen on September 23rd. I hope this timeline works with your 3.2 -> 3.3 OSDK migration plans.

**Comment by lvale** [comment]
@amenonDJI 
Thanks for the reply. Does a "preview" release exists that we can develop for ?

**Comment by amenonDJI** [comment]
@lvale It is still under development and will be based off of the 3.2 Local Position Control.

**Comment by JimTheKiwi** [comment]
Will the September 23rd release also include OSDK-ROS support for M600 RTK?  On the latest M600 firmware at that time?

I have tested 3.3.1 with the current M600 firmware (released last week), then downgraded the M600 firmware back to remain on SDK 3.2.2 until 3.3.x supports (at least) RTK data, with RTK precision fused into the Odometry of the local position.  If there is a timetable / roadmap of features becoming available that would help with my project planning and reduce time spent on rolling back firmware.

**Comment by prodrone-dev** [comment]
@amenonDJI 
Great news, thank you!

**Comment by amenonDJI** [comment]
@JimTheKiwi The next release will include support for RTK. As mentioned earlier, Local position Control will be based off of the previous 3.2 implementation. 

@prodrone-dev You're welcome.

**Comment by frontw** [comment]
@JimTheKiwi Hi! How did you downgraded M600? I have no firmware selection in Assistant, only last fw. Any hint? 
Thanks!

**Comment by JimTheKiwi** [comment]
@frontw For me Assistant showed previous firmware versions and performed the downgrade successfully.
I am using the latest DJI Assistant 2 "version v1.1.2" for Mac OSX.
I have an M600 not Pro, we added two A3 upgrade kits (before the M600 Pro was released).

**Comment by frontw** [comment]
Thanks! It's not working for me because I have pro, I guess. So now I forced to work with 3.3 ;-)
Btw, here is RTK data publish realization https://github.com/dji-sdk/Onboard-SDK-ROS/pull/130.
For 3.2, is RTK data already fused with gps and imu?

**Comment by JimTheKiwi** [comment]
@frontw The 3.2 topic /dji_sdk/odometry is a local position that includes RTK position accuracy and IMU attitude etc data, can't tell if the GPS is fused in since it has the same attributes as RTK (aka differential GPS).  This fused Odometry is a very nice feature for easily tracking tf frames (eg in rviz).  @amenonDJI said that the future 3.3 service will be based on the 3.2 code, that sounds great.

The 3.2.2 Odometry is not quite ROS standard, I wrote a translator node to reflect it to make it a right-handed coordinate system that ROS can rotate with static transforms to conform to the ROS standard.  It sounds like the 3.3.x rewrite with RTK will be directly ROS standard so I can remove my translations.  I am keen to try DJI's next release later this month.

**Comment by amenonDJI** [comment]
@prodrone-dev @lvale Local position topic support was released on Friday (8th September) along with a Local Position control example. 

RTK support will be available in the next release.

**Comment by lvale** [comment]
@amenonDJI Schedule for that? Sept 23rd ?

**Comment by amenonDJI** [comment]
@lvale Tentatively. We have other features planned for the next release. It may get pushed a week or two.

**Comment by WesleyYue** [comment]
@amenonDJI Any news on this or what the new scheduled release date might be?
