### ISSUE TITLE
MissionWpGetInfo service call does not return the waypoint information

### ISSUE THREAD

**Issue by tompe17** [dji-sdk/Onboard-SDK-ROS#125]
MissionWpGetInfo service call does not return the waypoint information (tested with M100). An array of MissionWaypoint are returned but all the values seems to be zero for the fields in the MissionWaypoints.

When the mission is finished the number of MissionWaypoint elements become zero which is good because that is the only way I found to detect when the mission was finished.

**Comment by zliDJI** [comment]
Hi @tompe17.  We've verified your findings about the incomplete individual waypoint information from MissionWpGetInfo call. We'll fix this soon. Thanks!
