### ISSUE TITLE
Wrong topic for velocity control

### ISSUE THREAD

**Issue by tompe17** [dji-sdk/Onboard-SDK-ROS#126]
In demo_flight_control.cpp the line
`ctrlVelYawRatePub = nh.advertise<sensor_msgs::Joy>("dji_sdk/flight_control_setpoint_generic", 10);`
should be
`ctrlVelYawRatePub = n.advertise<sensor_msgs::Joy>("dji_sdk/flight_control_setpoint_ENUvelocity_yawrate", 10);`

**Comment by zliDJI** [comment]
Hi, @tompe17  Thanks for the finding. The topic type of ctrlVelYawRAtePub was set to flight_control_setpoint_generic intentionally. But when we sent the command, there was a bug. Line 172-176, and line 182, should have been in "else if(break_counter > 0)", i.e.,

```
  else if(break_counter > 0)
  {
  sensor_msgs::Joy controlVelYawRate;

    uint8_t flag = (DJISDK::VERTICAL_VELOCITY   |
                    DJISDK::HORIZONTAL_VELOCITY |
                    DJISDK::YAW_RATE            |
                    DJISDK::HORIZONTAL_GROUND   |
                    DJISDK::STABLE_ENABLE);

    controlVelYawRate.axes.push_back(0);
    controlVelYawRate.axes.push_back(0);
    controlVelYawRate.axes.push_back(0);
    controlVelYawRate.axes.push_back(0);
    controlVelYawRate.axes.push_back(flag);

    ctrlVelYawRatePub.publish(controlVelYawRate);
    break_counter++;
    return;
  }
  else //break_counter = 0, not in break stage
  {
    sensor_msgs::Joy controlPosYaw;
    controlPosYaw.axes.push_back(xCmd);
    controlPosYaw.axes.push_back(yCmd);
    controlPosYaw.axes.push_back(zCmd);
    controlPosYaw.axes.push_back(yawDesiredRad);
    ctrlPosYawPub.publish(controlPosYaw);
  }
```
We'll push a hotfix later. Thanks!

**Comment by tompe17** [comment]
For me the name ctrlVelYawRatePub was the confusing thing. I assumed from the name how it should work when I copied some code from the sample.
