### ISSUE TITLE
Do you plan to add DJIDrone class for 3.3 to wrap ROS topsics and services communication as it was in 3.2?

### ISSUE THREAD

**Issue by frontw** [dji-sdk/Onboard-SDK-ROS#131]
Hi!
Do you plan to add DJIDrone class for 3.3 to wrap ROS topsics and services communication as it was in 3.2?
Demos code seems like I'll need to organize ROS communication (topics monitoring and publishing) myself.
It's OK, just want to know, what would be usual way, because it seems to be changed from 3.2.

**Comment by zliDJI** [comment]
Hi, @frontw   Currently we are not planning to add DJIDrone class. As you know, DJIDrone class is a wrapper of the topics and services provided by dji_sdk_node, which itself is a wrapper of the dji onboardsdk core.  By having less layers we tried to make the interfaces easy to understand by most ROS users.
