### ISSUE TITLE
gps_position topic of sensor_msgs/NavSatFix type has no NavSatStatus status value set

### ISSUE THREAD

**Issue by frontw** [dji-sdk/Onboard-SDK-ROS#132]
I want to use this flag to filter not valid GPS data, but find that it is not set and separate gps_health topic is published.
I think, it would be better to set this flag in NavSatFix msg.
My question is, how to find correlation between ROS NavSatStatus flags and DJI gps_health uint8 value.
I only found this "GPS signal health is between 0 and 5, 5 is the best condition. Use gps_position for control only if gps_health >= 3."
ROS NavSatStatus has following format (http://docs.ros.org/api/sensor_msgs/html/msg/NavSatStatus.html):
```
 # Navigation Satellite fix status for any Global Navigation Satellite System

# Whether to output an augmented fix is determined by both the fix
# type and the last time differential corrections were received.  A
# fix is valid when status >= STATUS_FIX.

int8 STATUS_NO_FIX =  -1        # unable to fix position
int8 STATUS_FIX =      0        # unaugmented fix
int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation
int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation

int8 status

# Bits defining which Global Navigation Satellite System signals were
# used by the receiver.

uint16 SERVICE_GPS =     1
uint16 SERVICE_GLONASS = 2
uint16 SERVICE_COMPASS = 4      # includes BeiDou.
uint16 SERVICE_GALILEO = 8

uint16 service

```
Is there any way to fill status and service values?

**Comment by amenonDJI** [comment]
@frontw 
The status in NavSatFix msg is not fully exposed to the Onboard SDK. We can tell if the status was FIX or NO_FIX but at the moment cannot tell if it is SBAS FIXED or DGPS fixed. 

The gps_health topic has more information (0 - 5 health). Please use gps_health to monitor gps state.
