### ISSUE TITLE
dji_sdk_node.cpp line 311, align_time_with_FC is true, not false

### ISSUE THREAD

**Issue by longlongagox** [dji-sdk/Onboard-SDK-ROS#133]
dji_sdk_node.cpp line 311
ROS_INFO("align_time_with_FC set to false. We will time stamp messages based on flight controller time!");

should be 

ROS_INFO("align_time_with_FC set to **true**. We will time stamp messages based on flight controller time!");

**Comment by zliDJI** [comment]
Thank you for the report! We'll fix it.
