### ISSUE TITLE
Gimbal control and feedback data seems to have different reference

### ISSUE THREAD

**Issue by frontw** [dji-sdk/Onboard-SDK-ROS#137]
Yaw data seems to have some bias.

When I set yaw to 0, I get -59 deg, when I set 20, I get -39. See screenshots. Roll and pitch are controlled normally. 

![screenshot from 2017-09-07 14-39-27](https://user-images.githubusercontent.com/14126078/30161786-ada7a85a-93da-11e7-9e4f-933a945bace2.png)
![screenshot from 2017-09-07 14-39-53](https://user-images.githubusercontent.com/14126078/30161787-ada94372-93da-11e7-9b7b-74bdd5ff05b8.png)

I think, there is some problem with gimbal reference, it's different for control and feedback topic, but should be the same.

Note: I removed DEG2RAD according to #136.

**Comment by rohitsantdji** [comment]
The yaw angle reported by the gimbal is in an absolute (Earth-fixed) frame - so the values in yaw are with respect to absolute north.

**Comment by frontw** [comment]
Ok, then control should be in same frame, yes?

**Comment by zliDJI** [comment]
For control, there are multiple modes, with angle meaning different depending on the modes, please refer to the docs:

https://developer.dji.com/onboard-api-reference/structDJI_1_1OSDK_1_1Gimbal_1_1AngleData.html

**Comment by frontw** [comment]
Please, review my screenshots. If I give an angle of 20 degrees, for example, should I get the same (approximately) angle in feedback (as it is for roll and pitch, but not yaw)? Or I need to give control with one reference and get result with another?

**Comment by zliDJI** [comment]
You set bit 0 of mode to 1, which according to documentation in my link,  "Absolute control, the angle reference is related to configuration in DJI Go App". 

However, in DJI Go App, the default configuration is "Follow", meaning that the Yaw is with respect to body frame (see the docs in my link), so when you set yaw to 0 degree, gimbal will point to the nose of the drone.

**Comment by zliDJI** [comment]
Hi @frontw, we verified your finding and found that in "free" mode, the gimbal is not behaving the way as documented. The gimbal is moving with relative angles in both "free" and "follow" mode.
 We'll investigate the issue internally and get back to you. Thanks and sorry about the issue.
