### ISSUE TITLE
read camera data from DJI-GO and manifold

### ISSUE THREAD

**Issue by zhudelong** [dji-sdk/Onboard-SDK-ROS#14]
what do you mean by "The DJI Go has a power-saving strategy, users should either enter the camera view or **do not run DJI GO at first in order to get the video stream**. The video will be freezed if _uses _stay in the main screen of DJI GO."

if I use this package in manifold, will i get video from app? 
if i do not  use this package but share lib. -----libcam.so---- in manifold, can i get video both on app and manifold at the same time?
Thank you very much!

**Comment by lanyusea** [comment]
1. I updated the readme see if it is better to understand.

2. feature added. (check last two file of https://github.com/dji-sdk/Onboard-SDK-ROS/commit/c118626fd3df1f8fc75054152de7784888f1a26a)
