### ISSUE TITLE
Manual override for P/F mode switch Failed and obtain/release control is not working in 3.3.1

### ISSUE THREAD

**Issue by snakehaihai** [dji-sdk/Onboard-SDK-ROS#140]
Hi
I`m using new 3.3 api to control UAV autonomously using external sensor in indoor environment. 
for 3.2 control and bypass(using either switch P to F, or from obtain/release ctrl)  is fine. I can control UAV using Lidar and sent out control signal at P mode. anything wrong just switch to F mode. The only problem is with IMU update frequency is too low that I can not run vision-inertial based navigation with it. 

In 3.3 IMU is published at 400 hz which is ideal. When shit happens in P mode, I have to switch to F mode for the emergency manual override. However, the drone does not regain control from RC. May I ask how to solve this issue?

I tried release control by setting 0 to service /dji_sdk/sdk_control_authority, no ack on release API control in dji_sdk terminal.  In rqt_service_caller, I set  /dji_sdk/sdk_control_authority to both 0 and 1
 In dji_sdk terminal only shows STATUS/1 @ getErrorCodeMessage, L590: 
STATUS/1 @ getCMDIDSetControlMSG, L731: OBTAIN_CONTROL_SUCCESS

release ack never pop up in the dji_sdk terminal . and

 I checked in the code there is release ack code.

So I changed OSDK ROS service cpp file for debugging
ACK::ErrorCode ack;
  if (request.control_enable)
  {
    ack = vehicle->obtainCtrlAuthority(WAIT_TIMEOUT);
    ROS_DEBUG("called vehicle->obtainCtrlAuthority");
    std::cout<<"called vehicle->obtainCtrlAuthority"<<std::endl;
    std::cout<<ack.data<<std::endl;
  }
  else
  {
    ack = vehicle->releaseCtrlAuthority(WAIT_TIMEOUT);
    ROS_DEBUG("called vehicle->releaseCtrlAuthority");
    std::cout<<"called vehicle->releaseCtrlAuthority"<<std::endl;
    std::cout<<ack.data<<std::endl;
  }

it seems that obtain return ack always 2. which i suppose its bool true.  release return ack is always 1 which I think its bool false.
Then I looked into OSDK3.3.1. In the vehicle.cpp, it gets return status from A3 MCU/FCU.  So my best guess is there is return status error in either A3 MCU/FCU. 

Can you help to confirm this? And it could be better if you can provide me a solution for emergency override just in case of shit happens. 

BTW can you set this to a topic instead of service? So that I can bag it easily to verify the problem. Now seems a bit hard to troubleshoot. Have to go through log which is much more tedious

I`m using dji sdk 3.3.1 and lightbridge 2.

Regards
Shenghai Yuan

**Comment by rohitsantdji** [comment]
Please see #139 .

**Comment by snakehaihai** [comment]
confirm no use.
when shit happens. UAV carrying a payload of 1kg fly with 80-degree pitch angle flying towards the wall. 
I`m the main developer, In software control mode, for a brief time, I have control.  I tried to release software control-> no use.  Then i call service to release contorl. So that i can test emergency override

my assistant server as the Secondary pilot tried to disarm drone in both P mode and F mode. no use
He mention to me for a short period of time, He has control. after that then lost, and drone fly 80 degrees to the wall. 
We were panic. lucky drone is on our test rig and we know for 1st a few time shit happens.
Then we didn`t dare to do any more test. but to test out software response

and we notice that api can have control no matter in P or F mode for some reason. Will confirm this and take a picture to show you tmr

**Comment by rohitsantdji** [comment]
Are you using an A3/N3 on a custom vehicle, or an M600? Please note that as the docs on control authority say, the behavior is different for both cases. 

> But in flight, after I`m in API mode and switch back. and we notice that API can have control no matter in P or F mode for some reason. 

As i mentioned before, this is expected as per the docs. You should monitor the mode switch positions and send release/obtain control commands accordingly - here is a small snippet that works:

```
    //! Check RC commands for release control
    curRC = vehicle->broadcast->getRC();
    if (curRC.mode == 10000 && (!isRCToggle))
    {
      isRCToggle = true;
      DSTATUS("Releasing control..");
      vehicle->releaseCtrlAuthority(1);
    }
    if (curRC.mode == -10000 && (isRCToggle))
    {
      isRCToggle = false;
      DSTATUS("Releasing control..");
      vehicle->releaseCtrlAuthority(1);
    }
```
isRCToggle is a bool that maintains state.

For the other issue regarding dji_sdk/flight_control_setpoint_generic, please open a new issue since it is unrelated to this discussion and will help others if the two are kept separate.

**Comment by snakehaihai** [comment]
With lightbridge controller off->   called service vehicle->obtainCtrlAuthority  ack=2
                                                    called service vehicle->releaseCtrlAuthority ack=1
mode switch = P->   called service vehicle->obtainCtrlAuthority  ack=2
                                                    called service vehicle->releaseCtrlAuthority ack=1
mode switch = A->   called service vehicle->obtainCtrlAuthority  ack=2
                                                    called service vehicle->releaseCtrlAuthority ack=1
mode switch = F->   called service vehicle->obtainCtrlAuthority  ack=2
                                                    called service vehicle->releaseCtrlAuthority ack=1

Funny thing is, I remember in some cases, the red warning pop up say I can't obtain control in the dji driver. Just could not remember how I did it

**Comment by snakehaihai** [comment]
ok previous flight was not turn on enable multple flight mode flag.
but trickly thing is once i turn the flag on. restart drones follow thing happens


called vehicle->obtainCtrlAuthority
2
called vehicle->obtainCtrlAuthority
2
called vehicle->obtainCtrlAuthority
2
called vehicle->releaseCtrlAuthority
1
called vehicle->releaseCtrlAuthority
1
called vehicle->releaseCtrlAuthority
1
called vehicle->releaseCtrlAuthority
1
called vehicle->obtainCtrlAuthority
2
called vehicle->obtainCtrlAuthority
2
called vehicle->obtainCtrlAuthority
2
called vehicle->obtainCtrlAuthority
2
called vehicle->obtainCtrlAuthority
2
called vehicle->releaseCtrlAuthority
1
called vehicle->releaseCtrlAuthority
1
called vehicle->releaseCtrlAuthority
1
called vehicle->releaseCtrlAuthority
0

STATUS/1 @ getErrorCodeMessage, L590: 
STATUS/1 @ getCMDIDSetControlMSG, L724: RC_NEED_MODE_P

STATUS/1 @ getCMDIDSetControlMSG, L731: RC_MODE_ERROR
called vehicle->releaseCtrlAuthority
0

STATUS/1 @ getErrorCodeMessage, L590: sdkCtrlAuthorityCallback
STATUS/1 @ getCMDIDSetControlMSG, L724: RC_NEED_MODE_P

STATUS/1 @ getCMDIDSetControlMSG, L731: RC_MODE_ERROR
called vehicle->releaseCtrlAuthority
0

STATUS/1 @ getErrorCodeMessage, L590: sdkCtrlAuthorityCallback
STATUS/1 @ getCMDIDSetControlMSG, L724: RC_NEED_MODE_P

STATUS/1 @ getCMDIDSetControlMSG, L731: RC_MODE_ERROR
called vehicle->releaseCtrlAuthority
0

STATUS/1 @ getErrorCodeMessage, L590: sdkCtrlAuthorityCallback
STATUS/1 @ getCMDIDSetControlMSG, L724: RC_NEED_MODE_P

STATUS/1 @ getCMDIDSetControlMSG, L731: RC_MODE_ERROR
called vehicle->obtainCtrlAuthority
0


```

which is strange. for 1st round of P A F switching. software shows no error in obtain control and release control. for subsequent round. all error pops up.

**Comment by snakehaihai** [comment]
I verified again. upon start, UAV API can control, no matter what state it is. only upon start

**Comment by snakehaihai** [comment]
Hi i was flying and it went out of control. We verified the problem like below.
Although F mode does not allow API control. but even in F mode, RC is not working as well. 

the problem can be reproduced as follows
1. arm the drone in P mode. software can obtain and release the control.
2. while software obtain control,  switch from P to F mode.
it appear to be both software and lightbriedge RC dont have any control at all. emergency by pass is not working

only switch from F to P again. then use software control. then i can land the drone.

**Comment by snakehaihai** [comment]
dji error insufficient payload..then uav go to full throttle and pitch back mode, F mode by pass not working, API by pass not working. how to solve this

**Comment by rohitsantdji** [comment]
Is your multiple flight modes switch enabled in Assistant? If yes, what are your switch configurations?

**Comment by snakehaihai** [comment]
Yes I have to enable switch in order to achieve bypass right?  Mode are P A S. and in simulation everything is ok.

**Comment by snakehaihai** [comment]
To summary the errors.  
1.Error insufficient hover thrust blah blah blah -> A3 need enough payload for drone not to fucked up. 2.Possible multiple control mode problems -> Now i`m using P A G mode. 
3.P mode disables paradox -> From the manual when P is disabled, rc temporarily regained. I was sending command even it is 0 0 0 0 in regular 10hz basis that cause manual bypass not working. I have to put the publish(vel) inside the callback. as for possible traffic jam inside the callback only can be solved by a sending time filter to limit the number of output at each time.  So for autonomous control bypass in this 3.3 api, try not to publish control at the regular basis. as it might fucked up the bypass

After solved those problems, I managed to get it fly with pure SDK mode
