### ISSUE TITLE
ERRORS when increases number of waypoints in demo_mission.cpp

### ISSUE THREAD

**Issue by szx0112** [dji-sdk/Onboard-SDK-ROS#141]
I am running the waypoint demo on the upboard computer, when the number of waypoint is increased to 27, the error appear and says" ERROR, there is not enough memory". Then I take a look at the memory usage and find it only used 1000M/3.3G.

Any clue to solve this problem? Thanks.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
