### ISSUE TITLE
osdk-ros 3.3.1 dji_sdk_node.cpp small bug report

### ISSUE THREAD

**Issue by sky-github** [dji-sdk/Onboard-SDK-ROS#147]
osdk3.3.1 dji_sdk_node.cpp small bug report:
line 311: ROS_INFO("align_time_with_FC set to false. We will time stamp messages based on flight controller time!");
should be:
ROS_INFO("align_time_with_FC set to **true**. We will time stamp messages based on flight controller time!");_

**Comment by rohitsantdji** [comment]
This has already been fixed in 5e6f683.
