### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by gjd2017** [dji-sdk/Onboard-SDK-ROS#150]
\Onboard-SDK-3.3\sample\Qt\djiosdk-qt-sample\Subscribe\subscribe_panel.hpp(18): error C2536: “SubscribePanel::SubscribePanel::freqEnum”: 无法指定数组的显式初始值设定项

(windows7 64  SDK 3.3 QT5.6 DJI M100  )

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
