### ISSUE TITLE
set_local_pos_ref returns false but seems to work (in simulation)

### ISSUE THREAD

**Issue by tompe17** [dji-sdk/Onboard-SDK-ROS#151]
In simulation I get false from set_local_pos_ref:
`
lrs@mat0:~/lrs_ws/src$ rosservice call /dji0/dji_sdk/set_local_pos_ref
result: False
`
But the update seems to work and the data on the local_position topic looks OK.

**Comment by eeroniemi** [comment]
I noticed the same thing, would be nice to get True if setting local position was successful.

**Comment by amenonDJI** [comment]
@tompe17 @eeroniemi This issue will be fixed in the new release.

**Comment by amenonDJI** [comment]
Issue has been fixed in the latest release.
