### ISSUE TITLE
Cancel Landing feature request

### ISSUE THREAD

**Issue by sharvashish** [dji-sdk/Onboard-SDK-ROS#154]
Hello all,

Is there any API to cancel auto landing of vehicle, similar to one available in Mobile SDK.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
