### ISSUE TITLE
Missing Battery Information

### ISSUE THREAD

**Issue by fong7x7** [dji-sdk/Onboard-SDK-ROS#157]
When using an A3 with a custom lipo battery, there is no voltage, current, or capacity information provided by the battery topic.  The battery data should be coming into the A3 since I can see the voltage on DJI Assistant.

**Comment by zootboy** [comment]
This also affects me. I cannot use the latest version of the onboard SDK with ROS because it does not supply any battery information whatsoever. Version 3.3 supplies the voltage, however this feature was apparently removed in a578bdf8b for some reason.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
