### ISSUE TITLE
[M600][Pi]Download image from M600 to Raspberry Pi

### ISSUE THREAD

**Issue by dangviethieu-hntv** [dji-sdk/Onboard-SDK-ROS#160]
Hi there, I'm newbie. Sorry about my language. I have a question.
I connect Raspberry Pi 3 with M600. I take a picture. Now, I want to download image from SD card of M600 to SD card of Pi. How? 
Thanks !!!

**Comment by rohitsantdji** [comment]
Hi @dangviethieu-hntv , currently we unfortunately do not offer this functionality. To transfer images, you will need to physically remove the SD card from the drone and use a SD card reader to copy those images.

**Comment by dangviethieu-hntv** [comment]
Oh thank @rohitsantdji so much. I hope we have soon solutions!
