### ISSUE TITLE
Time is missing in RTK-topic

### ISSUE THREAD

**Issue by Dev-Rune** [dji-sdk/Onboard-SDK-ROS#170]
**Line 267 in file "dji_sdk_node_publisher.cpp".** 
The header (time-stamp and frame id) in the rtk_position message is not set. Please add:
```
  rtk_position.header.frame_id = "/gps";
  rtk_position.header.stamp    = msg_time;
```

Without these lines the header is empty, which makes it difficult to determine when the specific RTK-GPS position was measured.

**Comment by aybakana** [comment]
Did you resolve your problem? which version do you use? I cant even see RTK topics.

**Comment by Dev-Rune** [comment]
I forked the code (v. 3.3 i believe) and added the frame and timestamp to the file myself . I also made a pull request, but I had no response from the DJI-team, regarding this issue. They may have corrected this issue in newer versions.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
