### ISSUE TITLE
ROS API update request to add odometry and tf

### ISSUE THREAD

**Issue by frontw** [dji-sdk/Onboard-SDK-ROS#178]
Hi!

There are local position in ROS frame now, attitude message and so on. But it's bunch of topics not common used. I believe, we rather need odometry and tf topics.
Do you plan to add it?

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
