### ISSUE TITLE
DJI::onboardSDK::FlightData flight_ctrl_data wher can i find info about the flag ?

### ISSUE THREAD

**Issue by acdriec** [dji-sdk/Onboard-SDK-ROS#18]
Is there a file that explains what the flag means ?

DJI::onboardSDK::FlightData flight_ctrl_data;
flight_ctrl_data.flag = 0x90;

kind regards,
Dries

**Comment by lanyusea** [comment]
https://github.com/dji-sdk/Onboard-SDK/blob/3.1/doc/en/Appendix.md

**Comment by acdriec** [comment]
Is it the same as the control mode byte ? Thank you.

Kind regards

**Comment by lanyusea** [comment]
same

**Comment by acdriec** [comment]
Thanks lanyusea
