### ISSUE TITLE
3.6 read in x3 camera to node issue

### ISSUE THREAD

**Issue by tydb1** [dji-sdk/Onboard-SDK-ROS#181]
I am trying to read in my video feed from the x3 camera on my m100 with manifold. I need this in a ROS node and am using OSDK ROS 3.6. Is this still supported as there seems to only be a way to read manifold cam files up to OSDK ROS 3.2 and after this they seem to dissapear. How must I do it now using 3.6? Can I just download the old package and copy /dji_sdk_manifold_read_cam into my catkin_ws with v3.6?

**Comment by rohitsantdji** [comment]
Do give it a shot! We don't see any reason for this approach to fail. The manifold_read_cam package is completely independent from the rest of the SDK.
