### ISSUE TITLE
Failed to read from serial device

### ISSUE THREAD

**Issue by Niboros91** [dji-sdk/Onboard-SDK-ROS#184]
I am using Ubuntu 16.04, ROS Kinect, DJI ROS SDK 3.6 and DJI M600 Pro V1.00.01.65.

When I try to launch: $ roslaunch dji_sdk sdk.launch. I get the following error:

![dji_sdk error](https://user-images.githubusercontent.com/34307076/37146462-15175ddc-22c4-11e8-9e93-f744202caa20.PNG)

I have checked my serial port and cable, both are working fine with other devices, and I have also checked the baudrate (921600).
I tried as said here: dji-sdk/Onboard-SDK#176 and it didn't work 
Also doing: cat /dev/ttyUSB0 I get no data from the drone.
In dji Assistant I enable API sdk control and I am using the latest firmware.

PS: All this was working fine 2 weeks ago.

**Comment by rohitsantdji** [comment]
Did you get this resolved?

**Comment by asiron** [comment]
We were having the same problem. It doesn't work at all @ 921600 baud rate, but it works @ 115200, which can be insufficient if we want all the data at 100Hz. Setting manually baud rate through `stty -F /dev/ttyUSB0 921600` does not help neither.

**Comment by dji-kyle** [comment]
Please check the UART module/cables support baudrate up to 1000000
