### ISSUE TITLE
M210 - Dual Main cameras and Thermal image

### ISSUE THREAD

**Issue by soutieslak** [dji-sdk/Onboard-SDK-ROS#185]
I can successfully access the images of my main camera (Zenmuse X5s) and since the M210 has a dual mounting system for two main cameras, I want to know if it is possible to mount the Zenmuse XT (Thermal camera) on the other mount.

1. Can you have two Zenmuse x5s (two main cameras)? How would you distinguish between the two?
2. Can one of them be replaced by the Zenmuse XT (thermal camera)?
3. If I fly with only the Zenmuse XT mounted, will the thermal image come through? (Are the drivers the same for the Zenmuse x5s and XT?

Any help or comment would be appreciated.

**Comment by rohitsantdji** [comment]
Currently, the OSDK can only access camera streams from the camera that is on the gimbal labeled 'I', not the one labeled 'II'. Also, for the moment, we only support streams from the X4s, X5s and the newly-launched XT2 camera. For the older XT camera, we are looking into supporting it but do not have an ETA at this time.

**Comment by soutieslak** [comment]
Hi, thank you for the reply! Is there any ETA for OSDK support of camera streams from gimbal 'II'?

**Comment by guicolares** [comment]
Hi, 

Also is it possible get temperature for each Pixel and change some parameters from camera with onboard SDK ? 

Thanks

**Comment by alejodosr** [comment]
Hi @soutieslak I am trying to test the Zenmuse X4S (M210RTK V2) but without success, can you provide any insights about this topic? We are completely stuck, since we are running the official OSDK with supported devices and OS (Ubuntu 16.04). 

(I posted a wider explanation [this issue](https://github.com/dji-sdk/Onboard-SDK/issues/280)

**Comment by dji-kyle** [comment]
Please update the firmware to the latest and OSDK 4.1(for M210 v2 and M300)
