### ISSUE TITLE
unable to run Advanced Sensing - Stereo Images sample

### ISSUE THREAD

**Issue by QE2018** [dji-sdk/Onboard-SDK-ROS#187]
when we run rosrun dji_sdk_demo +tab we cannot find stereo images sample, but only the other six (i.e  demo_flight_control). can you tell me how can I get this one work?
thank you very much.

**Comment by rohitsantdji** [comment]
Did you compile your djiosdk-core library with the -DADVANCED_SENSING=ON flag, and then perform a `sudo make install`? If you have not done that, then recompile the core library in that manner, and clean out your build and devel directories in your catkin workspace as well. If that still doesn't show you the sample, post the output of your catkin_make here.

**Comment by rohitsantdji** [comment]
Closing since there has been no update for over 2 weeks. Please reopen if any questions remain.
