### ISSUE TITLE
No heading being outputted with ROS messages

### ISSUE THREAD

**Issue by pikachudetective** [dji-sdk/Onboard-SDK-ROS#188]
Looking through the wiki for published topics, there is no heading that's outputted from the DJI system. Since this is usually outputted by most other autopilots, is there a way DJI ROS can output this as a rostopic as well?

**Comment by rohitsantdji** [comment]
Heading is available through the dji_sdk/attitude message as part of the quaternion. You can convert from quaternion to Euler angles, the yaw component would be the heading.
