### ISSUE TITLE
Update README.md to latest firmware for M600

### ISSUE THREAD

**Issue by asiron** [dji-sdk/Onboard-SDK-ROS#194]
I have recently upgraded our M600's firmware to version `1.0.1.65` and I am getting some problems using the ROS SDK (#98). Is the new firmware supported by SDK version `3.6`?

**Comment by rohitsantdji** [comment]
Yes, the FW is supported with 3.6. Did you follow any "unlock" buttons that might have popped up in DJI Assistant 2 and in DJI Go?
