### ISSUE TITLE
flight_control_demo sets different points

### ISSUE THREAD

**Issue by a137755952** [dji-sdk/Onboard-SDK-ROS#195]
In gps_callback function, there is four points to go in order,but question is that why the drone only finished route 1. The log tells me that my node still publish the cmd msg by this code :ctrlPosYawPub.publish(controlPosYaw); And here is the log shows:
[ INFO] [1524209691.036979583]: ##### Route 1 start break....
[ INFO] [1524209691.537097328]: -----x=0.000480, y=19.737970, z=2.997893, yaw=1.046946 ...
[ INFO] [1524209691.537175781]: +++++dx=-0.000480, dy=0.262030, dz=0.002107, dyaw=-0.000251 ...
[ INFO] [1524209692.337567605]: -----x=0.001067, y=19.636650, z=2.997893, yaw=1.047160 ...
[ INFO] [1524209692.337648966]: +++++dx=-0.001067, dy=0.363350, dz=0.002107, dyaw=-0.000038 ...
[ INFO] [1524209692.557671130]: break_counter > 50
[ INFO] [1524209692.557761464]: ##### Route 1 finished....
[ INFO] [1524209692.577824086]: I am not doing square_mission.step()
[ INFO] [1524209692.577914352]: ##### Start route 2 ....
[ INFO] [1524209693.138026154]: xCmd = 2.000000 , yCmd = 2.000000 , zCmd = 10.987652 , yawDesiredRad = 1
[ INFO] [1524209693.158207613]: -----x=0.009883, y=-0.026735, z=0.027990, yaw=1.176792 ...
[ INFO] [1524209693.158408195]: +++++dx=19.990117, dy=5.026735, dz=9.972010, dyaw=-0.219471 ...
[ INFO] [1524209693.899978013]: xCmd = 2.000000 , yCmd = 2.000000 , zCmd = 10.987652 , yawDesiredRad = 1
[ INFO] [1524209693.938584535]: -----x=0.825810, y=0.698729, z=0.202474, yaw=1.426095 ...
[ INFO] [1524209693.938686852]: +++++dx=19.174190, dy=4.301271, dz=9.797526, dyaw=0.029832 ...
[ INFO] [1524209694.638938055]: xCmd = 2.000000 , yCmd = 2.000000 , zCmd = 10.987652 , yawDesiredRad = 1
[ INFO] [1524209694.678906490]: -----x=1.606457, y=1.381441, z=0.240433, yaw=1.443360 ...
[ INFO] [1524209694.679003858]: +++++dx=18.393543, dy=3.618559, dz=9.759567, dyaw=0.047097 ...
[ INFO] [1524209695.400764441]: xCmd = 2.000000 , yCmd = 2.000000 , zCmd = 10.987652 , yawDesiredRad = 1
[ INFO] [1524209695.439335032]: -----x=1.753618, y=1.431549, z=0.235353, yaw=1.433494 ...
[ INFO] [1524209695.439424571]: +++++dx=18.246382, dy=3.568451, dz=9.764647, dyaw=0.037231 ...

why does the drone is hovering without doing my points task?

**Comment by dji-kyle** [comment]
Please update the firmware to the latest and OSDK 3.9 + OSDK-ROS-3.8
