### ISSUE TITLE
Set Body Velocity

### ISSUE THREAD

**Issue by JamesUnicomb** [dji-sdk/Onboard-SDK-ROS#201]
Currently looking for a clever workaround besides publishing x,y velocities in ground frame coordinates from transforms (if this already exists in the API?).

**Comment by rohitsantdji** [comment]
You can publish to the `/dji_sdk/flight_control_setpoint_generic` and set the horizontal frame as body (FLU). You can find more information on the [DJI SDK ROS Wiki](http://wiki.ros.org/dji_sdk), scroll down to the very end of the page.
