### ISSUE TITLE
DJI Go with DJI Assistant 2 Simulator

### ISSUE THREAD

**Issue by sarathjayanthan** [dji-sdk/Onboard-SDK-ROS#209]
Hello,

 Is it possible to use DJI Go (in iOS or Android) and command the drone in DJI Assistant 2 Simulator? I am using DJI M600 Pro with On-Board Computer (with DJI SDK ROS Packages).

Thanks for any help.

**Comment by rohitsantdji** [comment]
Yes. Do note that the DJI Go control with Assistant 2 simulation is completely independent of Onboard SDK.

**Comment by sarathjayanthan** [comment]
Thank you for the reply. 

Actually, I would like to enable/disable 'Multiple Flight Mode' option for real-time flight (without simulator). I understand that it can be done through DJI Go. Is it possible to do the same with Onboard SDK?

**Comment by rohitsantdji** [comment]
You can monitor the mode switch state by subscribing to RC topics, or using the RC telemetry Broadcast data.
