### ISSUE TITLE
Timestamping in OSDK 3.6 for Images

### ISSUE THREAD

**Issue by qboticslabs** [dji-sdk/Onboard-SDK-ROS#211]
Hi 

In dji_sdk_node_publisher.cpp code, we noted that, the time alignment is not done for the image. The time stamp of the image is ros::Time::now(). Is there any plans to correct the time stamp of images, which will helps to synchronize the camera image to the gimbal angle.

Here is the line for adding time stamping in the images. 

 img.header.seq = recvFrame.recvData.stereoVGAImgData->frame_index;
  img.header.stamp = ros::Time::now(); // @todo

Regards
Lentin Joseph

**Comment by rohitsantdji** [comment]
This time stamping is currently unavailable from the aircraft's firmware. This will require a fairly major firmware change which is not on our roadmap for Q3 2018.
