### ISSUE TITLE
I can control M210 to fly during simulation,but why can not I doing it in the real world?

### ISSUE THREAD

**Issue by a137755952** [dji-sdk/Onboard-SDK-ROS#214]
the information I received is:
ERRORLOG/1 @ initPackageFromTopicList, L160: package [0] is being occupied.

ERRORLOG/1 @ initGimbal, L860: Failed to initialize subscription package!

STATUS/1 @ getErrorCodeMessage, L644: droneTaskCallback
STATUS/1 @ getCommonErrorCodeMessage, L714: UNKNOWN_ACK_ERROR_CODE

Is there anyone can help me? thanks

**Comment by snakehaihai** [comment]
I have controlled M210 with both LIDAR and vision based navigation system. The problem you have is a connection issue.  Could be a lot of thing, like assistant setup, baud rate,  there are too many possibilities. you need to provide more accurate information
