### ISSUE TITLE
Control the drone from topic in terminal

### ISSUE THREAD

**Issue by Mondo92** [dji-sdk/Onboard-SDK-ROS#219]
Hi everyone, 

I've a simple question: why I can't control the drone by sending command from the relative ROS topic in terminal? 
I'm trying to execute this code:

`rostopic pub -r 20 /dji_sdk/flight_control_setpoint_rollpitch_yawrate_zposition sensor_msgs/Joy "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
axes: [5.0, -0.3, 5.0, 0.0]
buttons: []"
`

I get no error but the drone doesn't move in simulation.
Thanks in advance!

**Comment by CWOA** [comment]
Is the message publication the only command you've issued?
If so, you'll need to activate your device via the service `/dji_sdk/activation` and also request control of the aircraft via `/dji_sdk/sdk_control_authority`.
Have a look in the examples for how to do this programatically
