### ISSUE TITLE
Manifold read X3 cam need root every time

### ISSUE THREAD

**Issue by Dooonut** [dji-sdk/Onboard-SDK-ROS#22]
When i am using read_cam node to read image from X3 by Manifold, it needs **root** to launch the node, the driver needs **root** to read and write USB port, so can i add rules file to `/etc/udev/rules.d`?
And if so, what this file should be looks like?

**Comment by lanyusea** [comment]
maybe login as root?

**Comment by YorksonChang** [comment]
Hey, @Dooonut .I'm faced with the same problem, I wanna launch the read_cam node when my Manifold starts up, but it needs root permission.Could you tell me your approach?

**Comment by lanyusea** [comment]
@YorksonChang  

check this:
http://answers.ros.org/question/165246/launch-node-with-root-permissions/
