### ISSUE TITLE
Getting local position

### ISSUE THREAD

**Issue by ulkesh11** [dji-sdk/Onboard-SDK-ROS#221]
In sdk version 3.6, how to get local position of the drone using instance of `DJI::OSDK::Vehicle`?
I am looking for a equivalent of the following done with sdk version 3.2
`DJIDrone drone(nh);`
`local_position = drone.local_position`

**Comment by vacky11** [comment]
@CWOA Thanks for the explanation. But as mentioned earlier i am looking for a way to access local_position value using instance of `DJI::OSDK::Vehicle`, not by subscribing to a topic. Do you know how can that be done?

**Comment by CWOA** [comment]
Im afraid not, I could be wrong but it sounds like you're operating in the onboard sdk, not the onboard **ROS** sdk (this repository), maybe ask your question in that one - https://github.com/dji-sdk/Onboard-SDK

**Comment by vacky11** [comment]
ok thanks. I am using Onboard-SDK-ROS
