### ISSUE TITLE
No "/dji_sdk/display_mode" message get published. 

### ISSUE THREAD

**Issue by yfzhang** [dji-sdk/Onboard-SDK-ROS#223]
Using OSDK 3.6 with latest firmware, but could not get "/dji_sdk/display_mode" message published.
Already use DJI assistant 2 to config all the available information to be published.

**Comment by rohitsantdji** [comment]
What aircraft and firmware are you using? Also, what is the baud rate you configured?

**Comment by yfzhang** [comment]
firmware version "v01.01.0911" as seen from dji assistant 2.
baudrate is 921600.
BTW, what's the difference between *firmware package version* and *firmware package version* as written somewhere in your official documentation?
