### ISSUE TITLE
Not able to start the camera stream using ROS service

### ISSUE THREAD

**Issue by imkhairulikhwan** [dji-sdk/Onboard-SDK-ROS#227]
Hi and good day, 

I tried to run the advanced sensing object detection as per link: 

https://developer.dji.com/onboard-sdk/documentation/sample-doc/advanced-sensing-object-detection.html

The connection seems to be successful, but I couldn't get any image displayed though. I did not connect with any camera e.g. x5s, so I am assuming the default camera for M210 should be set as FPV?

I have modified ros.yaml to use fpv_camera_images, and "cameraType: 0" when calling rosservice. 

![image](https://user-images.githubusercontent.com/4214164/44200220-a8816580-a178-11e8-947c-47c1e8a74b1d.png)

Thank you!

**Comment by rcabg** [comment]
Hey there,

Ros service for camera stream activation has its params in order to select fpv or main cam and activation/deactivation. Please check which are used in the ROS service call.

Also, check which image topic name is expected by the darknet ros node. Fpv and main camera have different topic names. 

Hope you find this helpful, 
Cheers.

**Comment by rcabg** [comment]
Hey again @imkhairulikhwan

I'm just remembering one thing. Do you have the RC On with dji go app opened?

One problem I came across was that if I didn't have the RC with dji go app working, Ros camera subscription would be successful, but no images would be published.

Using the command "rostopic hz {topic_name}" can be helpful to detect whether images are being published or not. When you are sure that camera is running right, let's check darknet node.

**Comment by rcabg** [comment]
Hello again,

Yes, you have to click Go Fly and be able to see the fpv video with your RC. Then, go to ROS and call the service as you have been doing.

An example of the rostopic hz command would be "rostopic hz /dji_sdk/fpv_camera_images". If images are being published, it will show their frequency.

If after all darknet is still waiting for images, go chech what image topics are expected for the node. "rqt_graph" command is useful to check how everything is connected.

Cheers.

**Comment by imkhairulikhwan** [comment]
Hello @rcabg ,

thank you for the details! I have tried to click Go Fly and able to see the fpv video in DJI GO app, then called the service. But I still do not receive any images though. 

When I tried to run the rostopic and rqt_graph, I got following below: It seems that the images are being published, is that right?

![image](https://user-images.githubusercontent.com/4214164/44263236-b9050f00-a250-11e8-93dc-6530634c5a35.png)

**Comment by rcabg** [comment]
Hi @imkhairulikhwan

Yes, images are being published now at 30fps. Do "rqt_image_view" in a new terminal and you will be able to see them live.

Now try to launch darknet node and check with rqt_graph whether is or not connected through the fpv topic with the dji_sdk node. If not, please check what image topic is expected by darknet.

Cheers

**Comment by imkhairulikhwan** [comment]
Hi @rcabg ,

sorry but it seems the command "rqt_image_view" was not found when I executed the command in the folder catkin_ws. 

Below is the screenshot of the rqt_graph, it seems that darknet is not connected to the fpv topic. Is there any way I can check what's image topic is expected by darknet? 

![image](https://user-images.githubusercontent.com/4214164/44315696-59c61b00-a459-11e8-9dcd-a622b394f377.png)


Thank you!
