### ISSUE TITLE
Not able to build using catkin_make for ROS 3.7

### ISSUE THREAD

**Issue by imkhairulikhwan** [dji-sdk/Onboard-SDK-ROS#229]
Hi and good day, 

I recently updated the latest Onboard SDK and Onboard SDK ROS 3.7 using following steps (I ensured both are using 3.7 by running git branch): 

https://developer.dji.com/onboard-sdk/documentation/sample-doc/sample-setup.html#ros-onboard-computer

However, I received error message when building using catkin_make:

![image](https://user-images.githubusercontent.com/4214164/44378997-7d12c800-a536-11e8-8d54-31bf184901b0.png)

**Comment by dangviethieu-hntv** [comment]
@imkhairulikhwan you also need update Onboard-SDK v3.7 in https://github.com/dji-sdk/Onboard-SDK
guideline: https://developer.dji.com/onboard-sdk/documentation/sample-doc/sample-setup.html#ros-onboard-computer

**Comment by imkhairulikhwan** [comment]
Hi @dangviethieu-hntv ,

thanks for the reply. However, I did update both Onboard-SDK and Onboard-SDK-ROS to v3.7 when I received the above error message.

**Comment by dangviethieu-hntv** [comment]
@imkhairulikhwan please try remove lib installed.
_sudo rm -r /usr/local/include/djiosdk
sudo rm -r /usr/local/lib/libdjiosdk-core.a_
And install Onboard-SDK v3.7 again.

**Comment by imkhairulikhwan** [comment]
Hi @dangviethieu-hntv , thanks for the prompt reply. Just a quick one, does that mean we couldn't run 3.6 and 3.7 in the same machine, at the same time? (without installing /uninstalling)

**Comment by dangviethieu-hntv** [comment]
@imkhairulikhwan Oh, that 's got be it.

**Comment by imkhairulikhwan** [comment]
I'm able to finish at 100% now when doing catkin_make. 

Thanks! @dangviethieu-hntv
