### ISSUE TITLE
New Feature in v3.7 ( GPS-denied situations )

### ISSUE THREAD

**Issue by dangviethieu-hntv** [dji-sdk/Onboard-SDK-ROS#230]
Hi there, I see that in "Release Notes for Onboard SDK 3.7" have feature: "**Local position in both GPS and GPS-denied situations**". But I review some change in code, I cannot found how we can get telemetry info in GPS-denied situations. Anyone can help me? Thanks very muchhhh !!!!
@zliDJI @rohitsantdji

**Comment by AlexisTM** [comment]
I guess you want this: https://developer.dji.com/onboard-api-reference/structDJI_1_1OSDK_1_1Telemetry_1_1LocalPositionVO.html
