### ISSUE TITLE
Roslaunch terminal : Process has died when trying to run Object Detection sample

### ISSUE THREAD

**Issue by imkhairulikhwan** [dji-sdk/Onboard-SDK-ROS#235]
Hi and good day, 

we were testing on the new M210 RTK for the above issue, but the process has shown error as per screenshot below when I tried to run the Object Detection sample:

![image](https://user-images.githubusercontent.com/4214164/45194344-31c21e80-b285-11e8-8322-f6e66d1c8023.png)

https://developer.dji.com/onboard-sdk/documentation/sample-doc/advanced-sensing-object-detection.html

Previously I was already able to run the sample in another M210 and solved the issue from the subscription in following thread #227 .

I have also turned on RC and connected with ios mobile  (and turned on DJI GO app), but when starting rosservice I got error message in another terminal (so there were two errors; process has died in roslaunch terminal and this one):

"ERROR: transport error completing service call: unable to receive data from sender, check sender's logs for details"

p/s: I forgot to highlight that for this test, I use both DJI OnBoard 3.7 and DJI OnBoard ROS 3.7 (while #227 was using 3.6 for both)

**Comment by dji-kyle** [comment]
Please update the firmware to the latest and OSDK 3.9 + ROS 3.8 for M210 v1, OSDK 4.1 + ROS 4.1 for M210 v2
