### ISSUE TITLE
RTK topics not published after upgrading to version 3.7

### ISSUE THREAD

**Issue by PaulKemppi** [dji-sdk/Onboard-SDK-ROS#236]
Topics /dji_sdk/rtk_position etc. are not published because in dji_sdk_node.cpp the command 

vehicle->subscribe->initPackageFromTopicList(PACKAGE_ID_5HZ, nTopicRTKSupport,
                                                   topicRTKSupport, 1, 10)

returns false. The data transmission rate is set to 10Hz via DJI Assistant 2. All the other topics are published as expected.

**Comment by droneboxid** [comment]
Hi Paul-same case with me. i change back to 3.3 version.

**Comment by aybakana** [comment]
Hi, I tried version 3.7 for a lot of time and had the same problem. I wish I saw this thread before. This issue should be stated in the Readme though.

**Comment by aybakana** [comment]
I contacted delelopers team and They told me that there is a bug in version 3.7. I am using version 3.6 now but still I can not see the RTK topics.  should D-RTK lights turn green to see RTK topics?

**Comment by PaulKemppi** [comment]
By downgrading to the version 3.6, one loses the new topics (e.g. visual odometry). Could this bug be corrected ASAP as I need the RTK position for my customer? We bought M210 RTK mainly because of the accurate position it provides, so this bug is really causing trouble to our development.

**Comment by aybakana** [comment]
In order to install a previous version of onboard sdk, do you I have to remove the installed one?
