### ISSUE TITLE
How can I know flight mission is finished?

### ISSUE THREAD

**Issue by Seonhoon-Lee** [dji-sdk/Onboard-SDK-ROS#237]
Hello,

I want to generate new mission automatically after previous mission finished, but I can't find a variable which informs mission is finished. Is there any method for knowing whether a mission is finished or not?

**Comment by aRealBanana** [comment]
For Android sdk its done like this
`
private WaypointMissionOperatorListener eventNotificationListener = new WaypointMissionOperatorListener() {
        @Override
        public void onDownloadUpdate(WaypointMissionDownloadEvent downloadEvent) {

        }

        @Override
        public void onUploadUpdate(WaypointMissionUploadEvent uploadEvent) {

        }

        @Override
        public void onExecutionUpdate(WaypointMissionExecutionEvent executionEvent) {

        }

        @Override
        public void onExecutionStart() {

        }

        @Override
        public void onExecutionFinish(@Nullable final DJIError error) {
            setResultToToast("Execution finished: " + (error == null ? "Success!" : error.getDescription()));
            if(error==null)
           {
               
            }
        }
    };
`

**Comment by dji-kyle** [comment]
mission callback:
setWaypointEventCallback
setWaypointCallback
