### ISSUE TITLE
Missing #prgram once in dji_sdk/dji_drone.h

### ISSUE THREAD

**Issue by sytelus** [dji-sdk/Onboard-SDK-ROS#24]
This header file needs to either have

#pragma once

OR

#ifndef __DJI_SDK_DRONE_H__
#define __DJI_SDK_DRONE_H__

//.....code

#endif

**Comment by lanyusea** [comment]
closed because we have updated all codes/docs about the onboard SDK to solve any possible problem.

please reopen the issue if you still suffer the same problem
