### ISSUE TITLE
Different behavior in Simulator and the real world. 

### ISSUE THREAD

**Issue by sarathjayanthan** [dji-sdk/Onboard-SDK-ROS#242]
I'm trying to build a test flight script that publishes to the `/dji_sdk/flight_control_setpoint_ENUvelocity_yawrate` topic and it works perfectly well in the simulator, but in the real world the drone just keeps ascending until stopped by the RC.

I have a script using the `/dji_sdk/drone_task_control` service to take off and the `/dji_sdk/sdk_control_authority` service to gain control authority which seem to work fine in both scenarios.

**Comment by snakehaihai** [comment]
expected.  put your drone on a rig. and start testing basic performance. I went through the same thing before
