### ISSUE TITLE
Setting the control flags in Python

### ISSUE THREAD

**Issue by kira-on** [dji-sdk/Onboard-SDK-ROS#257]
I writing autonomous control using python for DJI N3. How do I set the control flags in Python?

flag = (DJISDK::VERTICAL_VELOCITY   |
                DJISDK::HORIZONTAL_ANGLE |
                DJISDK::YAW_RATE            |
                DJISDK::HORIZONTAL_GROUND   |
                DJISDK::STABLE_ENABLE)
    controlVelYawRate.axes.push_back(xCmd)
    controlVelYawRate.axes.push_back(yCmd)
    controlVelYawRate.axes.push_back(zCmd)
    controlVelYawRate.axes.push_back(yawDesiredRad)
    controlVelYawRate.axes.push_back(flag)
    controlRPVelYawRate.publish(controlVelYawRate)

Thanks in advance!

**Comment by H-Paul** [comment]
@lanyusea Thank you very much. I will check.
