### ISSUE TITLE
Missing namespace fpr DJIDrone class

### ISSUE THREAD

**Issue by sytelus** [dji-sdk/Onboard-SDK-ROS#26]
DJIDrone class in dji_sdk/dji_drone.h is not enclosed in namespace. This causes the class to go in global namespace. It should be in DJI::onboardSDK namespace like other things.

Also dji_drone.h should have include guards like all other header files.

I would strongly suggest to review your other files for similar basic issues. It would be great if above two can be fixed ASAP however because its the main class.

**Comment by lanyusea** [comment]
closed because we have updated all codes/docs about the onboard SDK to solve any possible problem.

please reopen the issue if you still suffer the same problem
