### ISSUE TITLE
Why dji_sdk_dji2mav project folder has been removed after 3.2 release 

### ISSUE THREAD

**Issue by Aansh2** [dji-sdk/Onboard-SDK-ROS#260]
dji_sdk_dji2mav project  has been remove after  3.2 version. Can any one suggest alternate project of it or can I still use it to connect DJI drone N3 model to remote GCS?

**Comment by lanyusea** [comment]
I think you can still use it.

**Comment by petergerten** [comment]
I am also very interested in this. Can someone confirm if it is still working when used with the latest version? Any missing core functionality?

**Comment by petergerten** [comment]
Anyone working with this?

**Comment by petergerten** [comment]
@dji-kyle it would be much appreciate if you could at least provide **ANY** comment on the issue before closing. :-(

**Comment by dji-kyle** [comment]
@petergerten I am sorry, For N3 please update the OSDK version to 3.9 and ROS to 3.8, if there is any issues of the latest version, please create new.

**Comment by dji-kyle** [comment]
@petergerten I am sorry, For N3 please update the OSDK version to 3.9 and ROS to 3.8, if there are any issues, please create new. The old version will no longer provide technical support and maintenance.
