### ISSUE TITLE
DJI Onboard-SDK-ROS : How to change Telemetry Topics Subscription frequency

### ISSUE THREAD

**Issue by k-koh** [dji-sdk/Onboard-SDK-ROS#263]
In DJI Onboard-SDK-ROS, sdk push topics

    dji_sdk/attitude
    dji_sdk/angular_velocity_fused

in DJISDKNode::publish100HzData() with 100Hz

and push topics

    dji_sdk/vo_position
    dji_sdk/velocity
    dji_sdk/height_above_takeoff

in DJISDKNode::publish50HzData() with 50Hz.

But i find the result frequency for topics(vo_position, velocity, height_above_takeoff) only have 1Hz in matrice m210 rtk.

How to change Telemetry Topics Subscription frequency to receive thes topic data in high frequency?

**Comment by lanyusea** [comment]
It can be adjusted by the DJI Assistant 2 software as I remember.

**Comment by k-koh** [comment]
> It can be adjusted by the DJI Assistant 2 software as I remember.

Thank you for your reply.
I set baud_rate in DJI Assistant 2 , but it no affect.
when i set baud_rate = 921600 in sdk.launch, 
 i can not launch ros dji_sdk_node for drone activation error.
i debug activation error to find that dji sdk got empty rawACK in getDroneVersion().
![set_baudrate_in_assistant2](https://user-images.githubusercontent.com/10125455/53404190-7d65b180-39f8-11e9-95c0-ac71c75d9dc0.png)
![set_baudrate_in_sdk_launch](https://user-images.githubusercontent.com/10125455/53404198-80f93880-39f8-11e9-830b-85a520fc5917.png)
![failed_get_getdroneversion_in_rawack](https://user-images.githubusercontent.com/10125455/53404202-82c2fc00-39f8-11e9-8cfa-4fdef18785b1.png)

**Comment by lanyusea** [comment]
@k-koh not the baudrate, but the following data frequency

(correct me if I misunderstand your question)
