### ISSUE TITLE
gps_health topic is not being published by M210

### ISSUE THREAD

**Issue by sharvashish** [dji-sdk/Onboard-SDK-ROS#264]
Hello guys,

M210 is configured in DJI simulation mode via M210ConfigTool.
I am getting valid gps_position data but gps_health topic is publishing 0. The issue persists for both 'use_broadcast' values set to 'True' or 'False'.

My M210 firmware version is 3.3.10.10 and I am using the latest DJI OSDK (3.7).
Any help is appreciated.

**Comment by lanyusea** [comment]
where did you try it? It should be 0 if you're in a poor-GPS environment.

I suggest you open the simulator, which will provide a non-zero health value and try again.

**Comment by snakehaihai** [comment]
cant be. check if both OSDK and OSDK-ros is running.  if no gps should be 0. average should be 3 good should be 5.
