### ISSUE TITLE
GImbal Angle not publishing at 50 Hz.

### ISSUE THREAD

**Issue by rebellojason7** [dji-sdk/Onboard-SDK-ROS#265]
I am working with the Matrice 210 RTK and had a couple of questions related to it, specifically related to the OnBoard-SDK.

1) The dji_sdk/gimbal_angle topic seems to be publishing at only 5 Hz as opposed to the mentioned 50 Hz as advertised on github. How do I increase in the frequency ?

2) When trying to run the time sync, it takes quite a while to get the time sync and sometimes even fails to get the time sync correctly.

3) The camera for the front stereo pair are really poor. Is there anyway to get better quality static cameras for the DJI Matrice 210 RTK ?

Thanks

**Comment by lanyusea** [comment]
1. you can change the frequency setting in DJI Assistant 2
2. the sdk itself has less to do with the sync, possible a firmware issue. may upgrade/downgrade help? If not, I suggest you contact the dev@dji.com
3. no, as far as I know, the baudrate is too large to support for better quality
