### ISSUE TITLE
The Onboard-SDK-ROS，is there any difference between the M100 and other flight controls?

### ISSUE THREAD

**Issue by leebyee** [dji-sdk/Onboard-SDK-ROS#266]
I developed for A3 flight controller before, and just switch to M100 development recently. I find that there's  some difference between the two, for example, the codes in the demo_flight_control.cpp:
` 
 if(is_M100())
  {
    ROS_INFO("M100 taking off!");
    takeoff_result = M100monitoredTakeoff();
  }
  else
  {
    ROS_INFO("A3/N3 taking off!");
    takeoff_result = monitoredTakeoff();
  }` 
It is different of taking off logic between M100 and A3, and is there any difference else?
Thank you!

**Comment by snakehaihai** [comment]
not much difference at ur top level. follow the arming code inside with service caller. it should be fine

At bottom level there could be the difference, but that dont concern to u
