### ISSUE TITLE
Waypoint.msg Heading, what is the reference for this angle?

### ISSUE THREAD

**Issue by Adrianrr94** [dji-sdk/Onboard-SDK-ROS#267]
Greetings.

I would like to know which reference is being used for this angle. In the msg definition it says that the angle range is [-180,180], but doesn't say anything about the reference. North, East, West or South?

Thanks.

**Comment by lanyusea** [comment]
should be north, and clockwise positive

**Comment by Adrianrr94** [comment]
Thank you
