### ISSUE TITLE
Can not catkin_make Onboard-SDK-ROS

### ISSUE THREAD

**Issue by shadow418** [dji-sdk/Onboard-SDK-ROS#268]
I built along this page.

[https://developer.dji.com/onboard-sdk/documentation/sample-doc/sample-setup.html#linux-oes](url)

But, the following error occurred.
Do you know the solution?

![a](https://user-images.githubusercontent.com/16955558/56009802-10924680-5d1c-11e9-9612-413139250be0.png)

**Comment by snakehaihai** [comment]
hi koki are you sure ur OSDK and OSDK-ROS version are same?
OSDK in ur OS has to be compatible with OSDK-ROS
It is not a compatibility issue. then i`m guessing u are using the latest version. quit using the latest version, 3.6 and 3.7 are more mature.

**Comment by huangzonghao** [comment]
The changes introduced in onboard-sdk ver. 3.8 is causing problem here. If you need to run onboard-sdk-ros right away, rolling back to ver. 3.7 could be a temporary fix.

**Comment by lanyusea** [comment]
@huangzonghao good catch, I will see if I have time to give a fix

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 + ROS 3.8
