### ISSUE TITLE
ROS melodic version don't support?

### ISSUE THREAD

**Issue by slamlixiaodong** [dji-sdk/Onboard-SDK-ROS#271]
I compile the code on the ROS melodic version, the topic of controling MAV is invalid. How I run the code on the melodic? I find the topic can be subscribed by dji_sdk node, but the MAV is don't fly. gz#25592

**Comment by dji-dev** [comment]
> Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/25592'>Zendesk ticket #25592</a>:<br><br>Dear Customer,<br><br>Thank you for contacting DJI.<br><br>Sorry that we have not tested the ROS Melodic version, suggest you first use the Kinetic version and OSDK-ROS-3.8 for functional verification and testing.<br><br>Thank you for your understanding and support, hope you a delighted life.<br><br>Best Regards,<br>DJI SDK Support Team
