### ISSUE TITLE
Presentation about DJI-SDK

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [dji-sdk/Onboard-SDK-ROS#272]
Hi , i'm a beginner developer i wanna learning DJI-SDK , can u please send me a presentation about that. I prefere slide please  gz#25954

**Comment by dji-dev** [comment]
> Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/25954'>Zendesk ticket #25954</a>:<br><br>Dear Customer,<br><br>Thank you for contacting DJI.<br><br>You can sign up for a developer account on the DJI developer website: https://developer.dji.com/<br>Then read the documentation for DJI Onboard SDK for prerequisite preparation, hardware, and software environment setup https://developer.dji.com/onboard-sdk/<br>Next, you can start running sample according to the documentation and learn how to use the API.<br><br>Thank you for your understanding and support, hope you a delighted life.<br><br>Best Regards,<br>DJI SDK Support Team
