### ISSUE TITLE
妙算2和M600在在使用OnboardSdkRos的时候，妙算找不到M600的窜口标识

### ISSUE THREAD

**Issue by pzy2253999075** [dji-sdk/Onboard-SDK-ROS#274]
你好，我在M600 PRO 和 妙算2G 上测试Onboard SDK ROS版的时候，发现妙算识别不了M600 PRO的窜口，但是ROS的 launch文件启动需要此窜口标识，我在妙算终端输入 lsusb 和  ls /dev/tty* 都没有发现无人机的窜口（因为没有新窜口增加），请问如何解决呢，谢谢。具体描述可以查看下面几张图片：
![image](https://user-images.githubusercontent.com/15712923/62419361-ea205e80-b6b0-11e9-943d-1571c2fae09e.png)
![image](https://user-images.githubusercontent.com/15712923/62419365-f3113000-b6b0-11e9-941c-a745cbe4236f.png)
![image](https://user-images.githubusercontent.com/15712923/62419372-fefcf200-b6b0-11e9-8edc-37c7168c11d6.png)
![image](https://user-images.githubusercontent.com/15712923/62419374-0ae8b400-b6b1-11e9-9da4-fb461de7b9f0.png)

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26726'>Zendesk ticket #26726</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

有注意到您使用的使用Manifold2-G，如果使用UART，只能使用UART1连接到M600 Pro，设备名称为：ttyTHS2
建议您使用Manifold2前可以先详细阅读产品使用手册，了解相关必要信息和注意事项：https://dl.djicdn.com/downloads/manifold-2/20190528/Manifold_2_User_Guide_v1.0_CHS.pdf
 ![](https://djisdksupport.zendesk.com/attachments/token/t9BTm2I1AV2oDFWBevyjek7At/?name=inline-1675506094.png)
感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持

**Comment by pzy2253999075** [comment]
@dji-dev 谢谢，但是我有遇到新的问题
![image](https://user-images.githubusercontent.com/15712923/62470203-7d01eb80-b7cc-11e9-8584-42ea35a7341e.png)
这是我的M600 PRO 硬件版本以及SDK调试页面
![image](https://user-images.githubusercontent.com/15712923/62470260-a3c02200-b7cc-11e9-9f43-cec0d974f629.png)
![image](https://user-images.githubusercontent.com/15712923/62470334-cc481c00-b7cc-11e9-8ebe-dffbdc295d91.png)

请问这个怎么解决呢

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26726'>Zendesk ticket #26726</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

有注意到您使用的是M600 Pro，该机型不支持AdvancedSensing功能，因此需要把ADVANCED_SENSING功能关掉，可以修改dji_sdk_node.cpp的代码，参考操作如下： ![](https://djisdksupport.zendesk.com/attachments/token/mLMb2YwVBxKO9VIkpV7a7yMMg/?name=inline-1122641980.png)​
修改保存后，重新编译即可

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/mLMb2YwVBxKO9VIkpV7a7yMMg' target='zd_attach'>inline-1122641980.png</a>

**Comment by pzy2253999075** [comment]
@dji-dev 嗯 可以运行了，但现在我需要通过can窜口接妙算和无人机（uart0和1用于接其他设备），比如我接can0，那对应的设备窜口是哪个呢，再次感谢
![image](https://user-images.githubusercontent.com/15712923/62529016-6614d500-b870-11e9-9f64-c1b41d6f55db.png)

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26726'>Zendesk ticket #26726</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

需要注意的是 OSDK API 接口不支持CAN总线，建议您可以使用USB-TTL模块。
另外CAN设备在Linux下是网络设备，can0就是对应的设备名称。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持

**Comment by pzy2253999075** [comment]
@dji-dev 好的，谢谢，那M600的can接口和妙算的can接口相连也不支持是吧？

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/26726'>Zendesk ticket #26726</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

是的，M600的CAN接口暂不支持二次开发。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持

**Comment by JoenHune** [comment]
> Public comment from Bruce Cheung in [Zendesk ticket #26726](https://djisdksupport.zendesk.com/agent/tickets/26726):
> 
> 尊敬的客户，
> 
> 您好！感谢您联系DJI大疆创新。
> 
> 有注意到您使用的使用Manifold2-G，如果使用UART，只能使用UART1连接到M600 Pro，设备名称为：ttyTHS2
> 建议您使用Manifold2前可以先详细阅读产品使用手册，了解相关必要信息和注意事项：https://dl.djicdn.com/downloads/manifold-2/20190528/Manifold_2_User_Guide_v1.0_CHS.pdf
> ![](https://camo.githubusercontent.com/552a62eacb5c757807f422077e16baa5998298968aea4fcad2dd73f5a9f47710/68747470733a2f2f646a6973646b737570706f72742e7a656e6465736b2e636f6d2f6174746163686d656e74732f746f6b656e2f743942546d3249314156326f444657426576796a656b3741742f3f6e616d653d696e6c696e652d313637353530363039342e706e67)
> 感谢您的理解与支持,祝您生活愉快!
> 
> Best Regards，
> DJI大疆创新SDK技术支持

您好，那么请问CPU版本的妙算2，它的uart0口有办法调整为普通串口使用吗？外接usb2tty设备会太复杂了

**Comment by dji-kyle** [comment]
妙算2C uart0是预留用于debug的串口，固定波特率为115200，无法直接用于OSDK通信使用。
