### ISSUE TITLE
how to use  callback in onboardSdk 

### ISSUE THREAD

**Issue by pzy2253999075** [dji-sdk/Onboard-SDK-ROS#286]
@dji-dev  I want to know how to use  setWaypointEventCallback（），could someone give me  a demo  with  some code  ，I want  to  know whether my uav  has reached  a waypoint，thanks.

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/27250'>Zendesk ticket #27250</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

You can call setWaypointEventCallback to register the callback function. The code sample is as below.
 ![](https://djisdksupport.zendesk.com/attachments/token/598VcC3lGx4hojN0t3AwjW9oc/?name=inline-2085990225.png)​
In ROS you can add "setWaypointEventCallback" in the end of the function DJISDKNode::missionWpUploadCallback.

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/598VcC3lGx4hojN0t3AwjW9oc' target='zd_attach'>inline-2085990225.png</a>

**Comment by pzy2253999075** [comment]
@dji-dev got it ,thanks

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/27250'>Zendesk ticket #27250</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

It's our pleasure to answer your questions, good luck with the project.

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team
