### ISSUE TITLE
How to get the drone heading

### ISSUE THREAD

**Issue by chaitanyantr** [dji-sdk/Onboard-SDK-ROS#290]
How to get the drone heading in ROS,i want the drone heading info for the rotation matrix from FLU to ENU frame.

I'm sending the velocity commands in body frame of drone, but the local position i'm getting is with respect to ENU frame. 

I tried to get it done with attitude of drone which will give the drone pose in quaternion, so i tried to convert it euler(degress) ,With tf liibrary in ros.

But im getting value of 81.2 in yaw,when it is facing the North(compass north),and
getting the value of 8.9 in yaw ,when the drone is facing east(compass east)

What is the yaw value i'm getting above is telling , is it compass north..? or True North ..? 

#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from geometry_msgs.msg import QuaternionStamped
from sensor_msgs.msg import Imu
import tf

def euler_callback(data):

     quaternion = (data.x,data.y,data.z,data.w)

     euler = tf.transformations.euler_from_quaternion(quaternion)

     roll= euler[0]
    pitch = euler[1]
    yaw = euler[2]

    rospy.loginfo("roll_imu,pitch_imu,yaw_imu %s,%s,%s:",roll*180/3.14,pitch*180/3.14,yaw*180/3.14)

def listener():
   
    rospy.init_node('euler_drone_validation', anonymous=True)

    rospy.Subscriber("/dji_sdk/attitude",QuaternionStamped, euler_callback)
   

    rospy.spin()

if __name__ == '__main__':
    listener()

**Comment by chaitanyantr** [comment]
Thanks for response,but to get clarity what is the values i'm getting  from attitude yaw..!!..is it change in drone yaw with respect to ENU frame.?

**Comment by waltermayor** [comment]
HI
I have a matrice 600 and I am trying to use the ros package robot_localization  to obtain the pose of my drone. the robot_localization package need IMU data in ENU frame, but the topic /dji_sdk/imu from the drone is in FLU frame.

How can I set my IMU data from FLU to ENU?
