### ISSUE TITLE
Issue regarding acceleration_ground_fused and angular_velocity_fused

### ISSUE THREAD

**Issue by vanshilshah97** [dji-sdk/Onboard-SDK-ROS#292]
I have a M600 , and and have a query regarding the topic published dji_sdk/acceleration_ground fused and angular velocity fused
What actually the raw data of imu is being fused with if I have one IMU and GPS ?

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/27576'>Zendesk ticket #27576</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Do you mean the data of imu topic? The specific fusion algorithm process belongs to the flight control part, which is not open to the public, sorry I can't tell you the details. In addition, you can learn about the data sources of the imu topic through the following contents.
 ![](https://djisdksupport.zendesk.com/attachments/token/i5IH176RXKFYwIkz4yE8o0DYT/?name=inline1756194175.png)​

Thank you for your understanding and support, hope you a delighted life.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/i5IH176RXKFYwIkz4yE8o0DYT' target='zd_attach'>inline1756194175.png</a>
