### ISSUE TITLE
DJI Assistant 2 Simulator not starting

### ISSUE THREAD

**Issue by AbhishekGS-MW** [dji-sdk/Onboard-SDK-ROS#302]
I am not able to start the Simulator from the DJI Assistant 2 software. I have been using it for a while, and now suddenly the Start button is not responsive. Please let me know how to proceed.

The version of the DJI Assistant 2 is - V2.0.3

I have tried restarting the PC also, but it doesn't help. 

Below is the link to the screen capture video.

https://drive.google.com/file/d/1w3YbpdzwMzkYK6Hi30KlhCGzSse3vKS_/view?usp=sharing

![dji-assistant2-simulator-start-not-working](https://user-images.githubusercontent.com/44699070/66884863-1c730400-eff0-11e9-96a1-718c6c42d5b5.PNG)

**Comment by erenaud3** [comment]
Hi !

I don't own a N3, I am using a M600pro. But from what I am seeing, your simulation seems to work just fine. Are you expecting your drone to take off when you press Start ? If yes, that's not how that works: you must use the remote controller for it.

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/28891'>Zendesk ticket #28891</a>:<br><br>Hi! It is recommended that you send email to DJI after-sales technical support for this issue. They are more suitable to help you with it.
