### ISSUE TITLE
Does this SDK support control of velocity of three axises and yaw angle simultaneously?

### ISSUE THREAD

**Issue by MicroYY** [dji-sdk/Onboard-SDK-ROS#309]
I have a requirement that the velocity of three axises and the yaw angle(not yaw rate) should be taken as input. 
Velocity control is supported in `controlVelYawRate`, but yaw angle is not.
`controlPosYaw` supports yaw angle control, but i need to specify a position, which conflicts with `controlVelYawRate` that velocity control does not work.
Could you provide a solution?

**Comment by maxhofidrone** [comment]
Hi!
as far as I understand your needs, I think it should possible with the 
`/dji_sdk/flight_control_setpoint_generic` flight control topic. You can decide with the `FlightControlFlag` how your input should be handled (velocity + angle).

Best regards,
Max

**Comment by MicroYY** [comment]
> Hi!
> as far as I understand your needs, I think it should possible with the
> `/dji_sdk/flight_control_setpoint_generic` flight control topic. You can decide with the `FlightControlFlag` how your input should be handled (velocity + angle).
> 
> Best regards,
> Max

Oh.  I have tried this, and it really works!
Thanks!!!    ^_^
