### ISSUE TITLE
Issues with 0.1.8 Release

### ISSUE THREAD

**Issue by uwleahcim** [dji-sdk/Onboard-SDK-ROS#31]
I was testing out the 0.1.8 release and noticed that dji_sdk topics are completely broken (e.g. my /dji_sdk/gimbal topic is reads 0.0, 0.0, 0.0). Is there firmware update for the M100 that is suppose to coincide with the 0.1.8 release, am I missing anything, or 0.1.8 has bugs? Rolling back to 0.1.7 release fixed the topics.

Thank you

**Comment by lanyusea** [comment]
bug.

kicking the ass of @bobbyshashin , repairing.

**Comment by lanyusea** [comment]
@uwleahcim 

problem is: https://github.com/dji-sdk/Onboard-SDK-ROS/blob/3.1/dji_sdk_lib/src/DJI_App.cpp#L105 

    passData(*enableFlag, dataflag, &broadcastData.gimbal, pdata,
             sizeof(GimbalData) - (versionData.version == versionM100_23) ? 1 : 0, len);

should be 

    passData(*enableFlag, dataflag, &broadcastData.gimbal, pdata,
             sizeof(GimbalData) - ((versionData.version == versionM100_23) ? 1 : 0), len);

together with the battery following.

You can update it by yourself or wait for an upgrade from us.

**Comment by bobbyshashin** [comment]
Bug fixed. Thanks for the notification @uwleahcim
