### ISSUE TITLE
can not success to catkin_make

### ISSUE THREAD

**Issue by liu978079474** [dji-sdk/Onboard-SDK-ROS#311]
Hello, catkin_make failed.I use Manifold 2

Ubuntu 16.04.2
ROS kinetic
Error log:
collect2: error: ld returned 1 exit status
sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/build.make:137: recipe for target 'bin/djiosdk-cameragimbal-sample' failed
make[2]: *** [bin/djiosdk-cameragimbal-sample] Error 1
CMakeFiles/Makefile2:224: recipe for target 'sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/all' failed
make[1]: *** [sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
CMakeFiles/Onboard-SDK.dir/build.make:73: recipe for target 'Onboard-SDK-prefix/src/Onboard-SDK-stamp/Onboard-SDK-install' failed
make[2]: *** [Onboard-SDK-prefix/src/Onboard-SDK-stamp/Onboard-SDK-install] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Onboard-SDK.dir/all' failed
make[1]: *** [CMakeFiles/Onboard-SDK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at Onboard-SDK-ROS-3.8/dji_sdk/CMakeLists.txt:31 (find_package):
  By not providing "FindDJIOSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DJIOSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "DJIOSDK" with any
  of the following names:

    DJIOSDKConfig.cmake
    djiosdk-config.cmake

  Add the installation prefix of "DJIOSDK" to CMAKE_PREFIX_PATH or set
  "DJIOSDK_DIR" to a directory containing one of the above files.  If
  "DJIOSDK" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/29992'>Zendesk ticket #29992</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

It is recommended that you compile according to the steps indicated in the DJI OSDK development documentation, https://developer.dji.com/onboard-sdk/documentation/development-workflow/sample-setup.html#ros-onboard-computer
If a compilation error still occurs, it is recommended to provide a complete compilation log (including all commands executed).

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by liu978079474** [comment]
Tanke you for your reply!But I still have catkin_make unsuccessful.
log:
dji@manifold2:~/catkin_ws$ catkin_make
Base path: /home/dji/catkin_ws
Source space: /home/dji/catkin_ws/src
Build space: /home/dji/catkin_ws/build
Devel space: /home/dji/catkin_ws/devel
Install space: /home/dji/catkin_ws/install
####
#### Running command: "cmake /home/dji/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/dji/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/dji/catkin_ws/install -G Unix Makefiles" in "/home/dji/catkin_ws/build"
####
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/dji/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/dji/velodyne/devel;/home/dji/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/dji/velodyne/devel;/home/dji/catkin_ws/devel;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/dji/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - dji_sdk
-- ~~  - dji_sdk_demo
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'dji_sdk'
-- ==> add_subdirectory(Onboard-SDK-ROS-3.8/dji_sdk)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Using Finddjiosdk-core.cmake find djiosdk-core
-- DO NOT FIND THE djiosdk-core LIB, WILL TRY TO DOWNLOAD FORM GITHUB, COMPILE, INSTALL
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Onboard-SDK 3.8.1 path is /home/dji/catkin_ws/src/Onboard-SDK-ROS-3.8/cmake-modules/../Onboard-SDK-3.8.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dji/catkin_ws/src/Onboard-SDK-ROS-3.8/cmake-modules/build
Scanning dependencies of target Onboard-SDK
[ 12%] Creating directories for 'Onboard-SDK'
[ 25%] Performing download step (git clone) for 'Onboard-SDK'
Cloning into 'Onboard-SDK-3.8.1'...
Note: checking out '3.8.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 908f91a... Merge pull request #2 in OS/onboard-sdk from fix_readme to master
[ 37%] No patch step for 'Onboard-SDK'
[ 50%] Performing update step for 'Onboard-SDK'
[ 62%] Performing configure step for 'Onboard-SDK'
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/aarch64-linux-gnu/libusb-1.0.so
-- External library - DJI Advanced Sensing for stereo cameras
-- Found FFmpeg  installed in the system.
--  - Includes: 
--  - Libraries: /usr/local/lib/libavcodec.a;/usr/local/lib/libavformat.a;/usr/local/lib/libavutil.a;/usr/local/lib/libswscale.a;/usr/lib/aarch64-linux-gnu/libtheora.so;/usr/lib/aarch64-linux-gnu/libz.so
-- Compiling without WaypointV2 Core
-- AdvancedSensing sample is enabled
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/aarch64-linux-gnu/libusb-1.0.so

stereo-vision-single-thread-sample...-- Found OpenCV installed in the system, will use it to display image in AdvancedSensing APIs

--  - Includes: /opt/ros/kinetic/include/opencv-3.3.1-dev;/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv
--  - Libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_cvv;opencv_datasets;opencv_dpm;opencv_face;opencv_fuzzy;opencv_hdf;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto

stereo-vision-multi-thread-sample...
-- Found OpenCV installed in the system, will use it to display image in AdvancedSensing APIs
--  - Includes: /opt/ros/kinetic/include/opencv-3.3.1-dev;/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv
--  - Libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_cvv;opencv_datasets;opencv_dpm;opencv_face;opencv_fuzzy;opencv_hdf;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto

camera-stream-poll-sample...
-- Found OpenCV installed in the system, will use it to display image in AdvancedSensing APIs
--  - Includes: /opt/ros/kinetic/include/opencv-3.3.1-dev;/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv
--  - Libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_cvv;opencv_datasets;opencv_dpm;opencv_face;opencv_fuzzy;opencv_hdf;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto

camera-stream-callback-sample...
-- Found OpenCV installed in the system, will use it to display image in AdvancedSensing APIs
--  - Includes: /opt/ros/kinetic/include/opencv-3.3.1-dev;/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv
--  - Libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_cvv;opencv_datasets;opencv_dpm;opencv_face;opencv_fuzzy;opencv_hdf;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto

stereo-vision-depth-perception-sample...
-- Found OpenCV 3.3.1 installed in the system, will use it for depth perception sample
--  - Includes: /opt/ros/kinetic/include/opencv-3.3.1-dev;/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv
--  - Libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_cvv;opencv_datasets;opencv_dpm;opencv_face;opencv_fuzzy;opencv_hdf;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
-- Did not find ximgproc in OpenCV
-- Did not find viz3d in OpenCV
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found 9.0 CUDA installed in the system, will use it for depth perception sample
--  - Includes: /usr/local/cuda-9.0/include
-- Did not find required libraries, stereo vision depth perception sample will not be compiled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dji/catkin_ws/src/Onboard-SDK-ROS-3.8/Onboard-SDK-3.8.1-build
[ 75%] Performing build step for 'Onboard-SDK'
Scanning dependencies of target advanced-sensing
[  2%] Creating directories for 'advanced-sensing'
[  5%] Performing download step (git clone) for 'advanced-sensing'
Cloning into 'advanced-sensing'...
Branch advanced-sensing-2.0.3-armv8 set up to track remote branch advanced-sensing-2.0.3-armv8 from origin.
Switched to a new branch 'advanced-sensing-2.0.3-armv8'
[  7%] No patch step for 'advanced-sensing'
[ 10%] No update step for 'advanced-sensing'
[ 13%] Performing configure step for 'advanced-sensing'
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dji/catkin_ws/src/Onboard-SDK-ROS-3.8/Onboard-SDK-3.8.1-build/osdk-core/AdvancedSensing
[ 15%] Performing build step for 'advanced-sensing'
[ 18%] No install step for 'advanced-sensing'
[ 18%] Completed 'advanced-sensing'
[ 18%] Built target advanced-sensing
Scanning dependencies of target djiosdk-core
[ 21%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_ack.cpp.o
[ 23%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_broadcast.cpp.o
[ 26%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_camera.cpp.o
[ 28%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_command.cpp.o
[ 31%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_control.cpp.o
[ 34%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_error.cpp.o
[ 36%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_gimbal.cpp.o
[ 39%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_hardware_sync.cpp.o
[ 42%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_hotpoint.cpp.o
[ 42%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_mfio.cpp.o
[ 44%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_mission_manager.cpp.o
[ 47%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_mobile_communication.cpp.o
[ 50%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_mobile_device.cpp.o
[ 52%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_payload_device.cpp.o
[ 55%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_subscription.cpp.o
[ 57%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_vehicle.cpp.o
[ 60%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_version.cpp.o
[ 63%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_virtual_rc.cpp.o
[ 65%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/api/src/dji_waypoint.cpp.o
[ 65%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/protocol/src/dji_aes.cpp.o
[ 68%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/protocol/src/dji_open_protocol.cpp.o
[ 71%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/protocol/src/dji_protocol_base.cpp.o
[ 73%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/hal/src/dji_hard_driver.cpp.o
[ 76%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/hal/src/dji_log.cpp.o
[ 78%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/hal/src/dji_memory.cpp.o
[ 81%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/hal/src/dji_platform_manager.cpp.o
[ 84%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/hal/src/dji_thread_manager.cpp.o
[ 86%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/utility/src/dji_circular_buffer.cpp.o
[ 89%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/utility/src/dji_singleton.cpp.o
[ 89%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/platform/default/src/dji_memory_default.cpp.o
[ 92%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/platform/linux/src/linux_serial_device.cpp.o
[ 94%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/platform/linux/src/posix_thread.cpp.o
[ 97%] Building CXX object osdk-core/CMakeFiles/djiosdk-core.dir/platform/linux/src/posix_thread_manager.cpp.o
[100%] Linking CXX static library ../libs/libdjiosdk-core.a
[100%] Built target djiosdk-core
[ 87%] Performing install step for 'Onboard-SDK'
[sudo] password for dji: 
[  7%] Built target advanced-sensing
[ 38%] Built target djiosdk-core
Scanning dependencies of target djiosdk-cameragimbal-sample
[ 39%] Building CXX object sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/camera_gimbal_sample.cpp.o
[ 40%] Building CXX object sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/main.cpp.o
[ 41%] Building CXX object sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/__/common/dji_linux_environment.cpp.o
[ 42%] Building CXX object sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/__/common/dji_linux_helpers.cpp.o
[ 42%] Linking CXX executable ../../../bin/djiosdk-cameragimbal-sample
/usr/local/lib/libavcodec.a(libx264.o): In function `X264_frame':
/home/dji/ffmpeg/libavcodec/libx264.c:298: undefined reference to `x264_picture_init'
/usr/local/lib/libavcodec.a(libx264.o): In function `reconfig_encoder':
/home/dji/ffmpeg/libavcodec/libx264.c:281: undefined reference to `x264_encoder_reconfig'
/usr/local/lib/libavcodec.a(libx264.o): In function `X264_frame':
/home/dji/ffmpeg/libavcodec/libx264.c:432: undefined reference to `x264_encoder_encode'
/home/dji/ffmpeg/libavcodec/libx264.c:432: undefined reference to `x264_encoder_encode'
/home/dji/ffmpeg/libavcodec/libx264.c:438: undefined reference to `x264_encoder_delayed_frames'
/home/dji/ffmpeg/libavcodec/libx264.c:432: undefined reference to `x264_encoder_encode'
/usr/local/lib/libavcodec.a(libx264.o): In function `reconfig_encoder':
/home/dji/ffmpeg/libavcodec/libx264.c:196: undefined reference to `x264_encoder_reconfig'
/home/dji/ffmpeg/libavcodec/libx264.c:201: undefined reference to `x264_encoder_reconfig'
/home/dji/ffmpeg/libavcodec/libx264.c:208: undefined reference to `x264_encoder_reconfig'
/home/dji/ffmpeg/libavcodec/libx264.c:228: undefined reference to `x264_encoder_reconfig'
/home/dji/ffmpeg/libavcodec/libx264.c:234: undefined reference to `x264_encoder_reconfig'
/usr/local/lib/libavcodec.a(libx264.o):/home/dji/ffmpeg/libavcodec/libx264.c:221: more undefined references to `x264_encoder_reconfig' follow
/usr/local/lib/libavcodec.a(libx264.o): In function `X264_close':
/home/dji/ffmpeg/libavcodec/libx264.c:497: undefined reference to `x264_encoder_close'
/usr/local/lib/libavcodec.a(libx264.o): In function `X264_init':
/home/dji/ffmpeg/libavcodec/libx264.c:576: undefined reference to `x264_param_default'
/home/dji/ffmpeg/libavcodec/libx264.c:581: undefined reference to `x264_param_default_preset'
/home/dji/ffmpeg/libavcodec/libx264.c:606: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:640: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:699: undefined reference to `x264_levels'
/home/dji/ffmpeg/libavcodec/libx264.c:699: undefined reference to `x264_levels'
/home/dji/ffmpeg/libavcodec/libx264.c:739: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:740: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:741: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:742: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:790: undefined reference to `x264_param_apply_fastfirstpass'
/home/dji/ffmpeg/libavcodec/libx264.c:830: undefined reference to `x264_param_apply_profile'
/home/dji/ffmpeg/libavcodec/libx264.c:887: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:889: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:901: undefined reference to `x264_param_parse'
/home/dji/ffmpeg/libavcodec/libx264.c:919: undefined reference to `x264_encoder_open_157'
/home/dji/ffmpeg/libavcodec/libx264.c:928: undefined reference to `x264_encoder_headers'
/home/dji/ffmpeg/libavcodec/libx264.c:959: undefined reference to `x264_encoder_maximum_delayed_frames'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
/home/dji/ffmpeg/libavcodec/opusdec.c:346: undefined reference to `swr_is_initialized'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_flush_resample':
/home/dji/ffmpeg/libavcodec/opusdec.c:89: undefined reference to `swr_convert'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
/home/dji/ffmpeg/libavcodec/opusdec.c:378: undefined reference to `swr_close'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_frame':
/home/dji/ffmpeg/libavcodec/opusdec.c:187: undefined reference to `swr_is_initialized'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_init_resample':
/home/dji/ffmpeg/libavcodec/opusdec.c:135: undefined reference to `swr_init'
/home/dji/ffmpeg/libavcodec/opusdec.c:141: undefined reference to `swr_convert'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_frame':
/home/dji/ffmpeg/libavcodec/opusdec.c:201: undefined reference to `swr_convert'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_flush':
/home/dji/ffmpeg/libavcodec/opusdec.c:581: undefined reference to `swr_close'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_close':
/home/dji/ffmpeg/libavcodec/opusdec.c:605: undefined reference to `swr_free'
/usr/local/lib/libavcodec.a(opusdec.o): In function `opus_decode_init':
/home/dji/ffmpeg/libavcodec/opusdec.c:674: undefined reference to `swr_alloc'
/usr/local/lib/libavcodec.a(tiff.o): In function `tiff_uncompress_lzma':
/home/dji/ffmpeg/libavcodec/tiff.c:467: undefined reference to `lzma_stream_decoder'
/home/dji/ffmpeg/libavcodec/tiff.c:472: undefined reference to `lzma_code'
/home/dji/ffmpeg/libavcodec/tiff.c:473: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/build.make:137: recipe for target 'bin/djiosdk-cameragimbal-sample' failed
make[2]: *** [bin/djiosdk-cameragimbal-sample] Error 1
CMakeFiles/Makefile2:224: recipe for target 'sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/all' failed
make[1]: *** [sample/linux/camera-gimbal/CMakeFiles/djiosdk-cameragimbal-sample.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
CMakeFiles/Onboard-SDK.dir/build.make:73: recipe for target 'Onboard-SDK-prefix/src/Onboard-SDK-stamp/Onboard-SDK-install' failed
make[2]: *** [Onboard-SDK-prefix/src/Onboard-SDK-stamp/Onboard-SDK-install] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Onboard-SDK.dir/all' failed
make[1]: *** [CMakeFiles/Onboard-SDK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at Onboard-SDK-ROS-3.8/dji_sdk/CMakeLists.txt:31 (find_package):
  By not providing "FindDJIOSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DJIOSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "DJIOSDK" with any
  of the following names:

    DJIOSDKConfig.cmake
    djiosdk-config.cmake

  Add the installation prefix of "DJIOSDK" to CMAKE_PREFIX_PATH or set
  "DJIOSDK_DIR" to a directory containing one of the above files.  If
  "DJIOSDK" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/dji/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/dji/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/29992'>Zendesk ticket #29992</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Noticed that the error occurred when compiling and link djiosdk-cameragimbal-sample, so what version of FFMPEG are you using? It is recommended to install 2.8.15, and if the compilation error still occurs, it is recommended that you restore manifold2-G's default system.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
