### ISSUE TITLE
M210 V2    连接妙算2g  使用onboardsdk Ros

### ISSUE THREAD

**Issue by pzy2253999075** [dji-sdk/Onboard-SDK-ROS#315]
请问，m210的窜口怎么接到妙算上，我想要使用onboardsdk  ，还要开启advance sensing 
![image](https://user-images.githubusercontent.com/15712923/69717258-af9e6e00-1146-11ea-93ac-e4d124ab362b.png)
@dji-dev  可以帮忙解决下吗  ，我把m210的硬件版本降级到450，同时也enable API,波特率设置为921600，app_id 和 key  都是新创建的。连线我用这个连妙算的uart1和m210 v2 拓展接口（9引脚）的最右端，还是打开不了onboardsdk，报错说是无人机激活失败了。
![image](https://user-images.githubusercontent.com/15712923/69775145-d5715480-11d2-11ea-9fbb-59684cea9fdb.png)
![image](https://user-images.githubusercontent.com/15712923/69776750-6b5bae00-11d8-11ea-88ce-401bde72bd17.png)
![image](https://user-images.githubusercontent.com/15712923/69776829-ba094800-11d8-11ea-8c6b-83da18d9b4d3.png)

**Comment by pzy2253999075** [comment]
@dji-dev 可以帮忙解决下嘛

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/30247'>Zendesk ticket #30247</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

建议您可以参考DJI OSDK开发文档关于Hardware Setup，Software Environment Setup等部分内容。
https://developer.dji.com/cn/onboard-sdk/documentation/development-workflow/hardware-setup.html
https://developer.dji.com/cn/onboard-sdk/documentation/development-workflow/environment-setup.html

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持

**Comment by pzy2253999075** [comment]
@dji-dev   我按照那2个链接的流程做了，还是不行，报同样的错误。请问，首先我这个无人机到妙算端的连线正确吗，启动onboardsdk的时候应该不用打开遥控器和app吧

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/30247'>Zendesk ticket #30247</a>:<br><br>尊敬的客户，

您好！感谢您联系DJI大疆创新。

已在您的邮件（Ticket 30262）回复，请注意查收。
另外第一运行OSDK是需要进行激活操作，建议打开遥控器并连接手机运行DJI Pilot。

感谢您的理解与支持,祝您生活愉快!

Best Regards，
DJI大疆创新SDK技术支持
