### ISSUE TITLE
Horizontal frame clarification

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [dji-sdk/Onboard-SDK-ROS#32]
Hi,
I would like to clarify what are
0b00: horizontal frame is ground frame
0b01: horizontal frame is body frame
for the attitude control mode.

Thanks

**Comment by uwleahcim** [comment]
I don't know if you got an answer already, horizontal frame is ground frame and horizontal frame is body frame controls which way x-axis and y-axis points.

horizontal frame is ground frame
x --> North
y --> East

horizontal frame is body frame
x --> forward
y --> right

**Comment by lanyusea** [comment]
closed because we have updated all codes/docs about the onboard SDK to solve any possible problem.

please reopen the issue if you still suffer the same problem
