### ISSUE TITLE
I have some question about osdk-3.2.

### ISSUE THREAD

**Issue by xu0426** [dji-sdk/Onboard-SDK-ROS#320]
Q1:Is osdk-ros 3.2.0 still available?
Q2:I try to launch dji_sdk manifold.launch (but I launch it in my own computer)，the terminal display :""SDK version did not match\n""
Can you help me ?

**Comment by dji-dev** [comment]
Public comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/31326'>Zendesk ticket #31326</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Sorry that version 3.2 of DJI OSDK-ROS is not recommended and no longer provides technical support. It is recommended that you use the master version of OSDK-ROS.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
