### ISSUE TITLE
Add nmea_msgs to the find_package() in CMakeLists.txt

### ISSUE THREAD

**Issue by BuriKizilkaya** [dji-sdk/Onboard-SDK-ROS#327]
If you compile with catkin build, you should note that the devel space layout is set to merged. Otherwise it is not possible to compile the dji_sdk with catkin build. If you add the entry nmea_msgs to CMakeLists.txt under find_package(), then it is no problem to compile the dji_sdk in the linked devel space.

Therefore my question why nmea_msgs was not listed under find_package.

**Comment by dji-dev** [comment]
Agent comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/33073'>Zendesk ticket #33073</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

Thank you for your feedback and suggestions. We will make a further confirmation and inform you as soon as there is any result.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
