### ISSUE TITLE
Can I use invdia TX2 as the onboard computer?

### ISSUE THREAD

**Issue by SHILAIFU** [dji-sdk/Onboard-SDK-ROS#328]
Hello, I am new to this. I have a question.
Can I use invdia TX2 as the onboard computer to control the M100?

**Comment by dji-dev** [comment]
Agent comment from Bruce Cheung in <a href='https://djisdksupport.zendesk.com/agent/tickets/33074'>Zendesk ticket #33074</a>:<br><br>Dear Customer,

Thank you for contacting DJI.

DJI Onboard SDK supports M100 and ARM v8 architecture onboard computer, so you can use invidia TX2.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by lorenzave** [comment]
I can confirm as we also use TX2 no problem.
