### ISSUE TITLE
Should I lock the variables in dji_drones.h when I read them?

### ISSUE THREAD

**Issue by zhudelong** [dji-sdk/Onboard-SDK-ROS#33]
I include the dji_drone.h in my own project and use AsyncSpinner spinner(4) to handle all the callback functions. Then i read variables that I need in my project. Since the callback handler thread and my main thread is not the same one, should I perform "add lock" and "release lock" operation to the related variables? Can you provide me with some ideas? Thank you very much！

**Comment by lanyusea** [comment]
closed because we have updated all codes/docs about the onboard SDK to solve any possible problem.

please reopen the issue if you still suffer the same problem
