### ISSUE TITLE
Camera services and topics not showing up

### ISSUE THREAD

**Issue by lpaula16** [dji-sdk/Onboard-SDK-ROS#334]
I'm trying to get camera stream from my M210 RTK V2, but none of the camera services or topics appear in the list. I've installed the SDK twice by now with the same error, so I don't think I messed up in the installation processes (ADVANCED_SENSING included)

I'm using Ubuntu 16.04
Ros Kinetic
SDK 3.8.1

![image](https://user-images.githubusercontent.com/23309087/82217444-b7331880-991a-11ea-9533-6969e606ba7f.png)

Thanks in advance!

**Comment by dji-dev** [comment]
Dear Cutomer,

Thank you for contacting DJI.

Note from the screenshot you provided that there is no prompt "Advanced Sensing is Enabled on M210" when starting roslaunch dji_sdk.
Therefore, please kindly confirm the development of platform architecture. Currently, the Advanced Sensing function only supports armv8 and x86.
And check the following two positions:
1. External_djiosdkcore.cmake
​
![image](https://user-images.githubusercontent.com/11869194/83252853-8b4b4900-a1de-11ea-8e25-c1fca8099228.png)

2. dji_sdk_node.cpp
​
![image](https://user-images.githubusercontent.com/11869194/83252876-9605de00-a1de-11ea-9262-6a89698989c3.png)

Then, recompile by executing the following command
$ cd catkin_ws
$ rm -rf build
$ catkin_make

If the problem persists, it is recommended that you post your full compiled log, as well as the full log of roslaunch.
