### ISSUE TITLE
Attitude Control HORI_POS

### ISSUE THREAD

**Issue by skyritsis** [dji-sdk/Onboard-SDK-ROS#34]
Hello,
In the examples, the attitude control is within a loop. But from what I can understand if someone wants to work with HORI_POS flag, the developer should just send one command with the offset in meters and wait for it to be finished. Though, when simulating this, it does not seem to work as intended.
Is there something I am missing?
Thank you in advance,
-SK

**Comment by lanyusea** [comment]
your understanding is incorrect

**Comment by skyritsis** [comment]
That, I can see. Though you did not seem to clarify what I am missing.

**Comment by lanyusea** [comment]
it should be in a loop, as mentioned in the document

**Comment by lanyusea** [comment]
every control command will execute the drone for 0.02 second, no matter position, velocity or attitude. 

therefore, you need to update the position offset and send the updated offset to the drone in 50 Hz

**Comment by skyritsis** [comment]
Thank you very much. This was brilliant.
Good day.
