### ISSUE TITLE
Make way point mission in the demo dynamic

### ISSUE THREAD

**Issue by uwleahcim** [dji-sdk/Onboard-SDK-ROS#35]
Was just browsing through changes and noticed something in the demo that can be improved a bit for the way point mission demo. This should make the way point mission dynamically perform zig-zag from its current position.

/dji_sdk_demo/src/client.cpp - line: 499

                // Currently hard coded, should be dynamic
                //static float orig_lat = 22.5401;
                //static float orig_long = 113.9468;
                static float orig_lat = drone->global_position.latitude;
                static float orig_long = drone->global_position.longitude;

There quite a few things that can be changed to improve the user experience of the dji_sdk_demo especially for beginners trying to study the demo for examples. When I have time I can clean up my highly modified (and messy) demo code, which I used to study the DJI SDK.

**Comment by amenon7** [comment]
@uwleahcim In the coming releases you will see improvements in the demo code - the focus will be to make the code more readable, to implement as many features in the Open Protocol and to add Doxygen compliant code comments. Some of the demo examples will also be tested in the real world. Feel free to submit a pull request for your code and we can merge them as necessary.
