### ISSUE TITLE
Please help me "cmake fail" , how to fix it?

### ISSUE THREAD

**Issue by TopKruZ** [dji-sdk/Onboard-SDK-ROS#358]
I already installed Install DJI SDK and next step Setup the DJI SDK ROS package

but when i "catkin_make" it failed , please help me.

and in the package why don't have "dji_osdk_demo" pagkage it only have "dji_osdk_ros"

![image](https://user-images.githubusercontent.com/50898222/87275377-25a1ea80-c508-11ea-9918-59490cb74d44.png)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/36827'>Zendesk ticket #36827</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Have you installed the Dependent Software ? And you can  referenced to : https://developer.dji.com/onboard-sdk/documentation/quickstart/development-environment.html

If the problem remains unsolved, suggest that comfirm and provide the version of OSDK and OSDK-ROS, which should be used with compatible version, such as OSDK4.0 with ROS4.0， OSDK3.9（3.8）with ROS3.8

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by pavankumarbn** [comment]
@TopKruZ Just run the command: sudo apt-get install ros-"distro"-nmea-msgs

**Comment by TopKruZ** [comment]
Hi, I need to ask some question OSDK and OSDK-ROS it support DJI Marvic Air2?

ส่งจาก iPad ของฉัน

เมื่อ 14 ก.ค. 2563 เวลา 13:04 เขียนโดย Pavan Kumar B N <notifications@github.com>:

﻿

@TopKruZ<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTopKruZ&data=02%7C01%7C%7C57e73f42fffa441db4c208d827bbc115%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637303034631000725&sdata=%2BvJww3gqnfxXvsNfR1LyyiClny8ZIXstOCwzNKKxiS8%3D&reserved=0> Just run the command: sudo apt-get install ros-"distro"-nmea-msgs

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/36827'>Zendesk ticket #36827</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry the OSDK and OSDK-ROS not support DJI Marvic Air2, And the list of OSDK supported models is available on the developer's website:
https://developer.dji.com/products/#!/onboard

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
