### ISSUE TITLE
Do you support DJI marvic air 2?

### ISSUE THREAD

**Issue by TopKruZ** [dji-sdk/Onboard-SDK-ROS#359]
Do you support DJI marvic air 2?

If it support DJI Marvic air 2 , how to connect the drone to OSDK , OSDK-ROS ?

I need to use DJI Marvic air 2 with darknet_yolo, if not support can you advise me how to use yolo with DJI Marvic air 2.

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/37047'>Zendesk ticket #37047</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry the OSDK(ROS) not support the DJI mavic air 2, About the drone type supported by Onboard SDK(ROS) , you can find in dev-website: https://developer.dji.com/products/#!/onboard

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
