### ISSUE TITLE
request update documents

### ISSUE THREAD

**Issue by snakehaihai** [dji-sdk/Onboard-SDK-ROS#360]
as shown in image

![image](https://user-images.githubusercontent.com/6070995/87962928-8de56300-caea-11ea-81ab-54e41b96b2af.png)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/37127'>Zendesk ticket #37127</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Thank you for your reminding. We will correct this error message later.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
