### ISSUE TITLE
Is there any apis for users to start simulations instead of using DJI simulators

### ISSUE THREAD

**Issue by qorost** [dji-sdk/Onboard-SDK-ROS#37]
Hi,

It is not convenient to debug apps with the DJI simulator if we are testing for different points, so I wonder if there is any access to the enable simulating through api or scripts ?

**Comment by amenon7** [comment]
Not entirely sure what you would like to Simulate - could you elaborate what you mean by "different points". Do you mean different GPS start locations?

**Comment by qorost** [comment]
Yes, I mean that.

**Comment by amenonDJI** [comment]
@qorost If you mean different GPS start locations, this can be entered in the Simulator itself. The page where you say "Start Simulation" has a spot to enter start GPS.
