### ISSUE TITLE
Is M600 supported

### ISSUE THREAD

**Issue by chukcha2** [dji-sdk/Onboard-SDK-ROS#38]
In the code, I see a lot of references to M100, but non for M600. Is M600 supported?

**Comment by amenon7** [comment]
The M600 is powered by an A3 flight controller. By changing the "M100" aircraft name in the sdk_manifold.launch file to "A3", you can fly the M600. Please keep in mind that the M600/A3 is in Beta support. The ROS functionalities have been tested in Simulation but has never been tested on a real aircraft. In a future release, we will have full support of A3/M600.
