### ISSUE TITLE
Mavic Mini Support

### ISSUE THREAD

**Issue by TomasMerva** [dji-sdk/Onboard-SDK-ROS#392]
Hi, I would like to ask you if there will be Onboard-SDK-ROS support for the Mavic Mini drone. If not, is there any way how I could control it from PC (especially using ROS) or could you point me to the direction how I could create something that would work?  

Thank you for your help.

**Comment by dji-dev** [comment]
Agent comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/39049'>Zendesk ticket #39049</a>:<br><br>The OSDK will only work when a drone can carry an external onboard computer - only the Matrice series drones are capable of this. All the other drones are too light and lack the input/output hardware.  So in short the Mavic Mini  is not supported by the OSDK and is only currently compatible with DJIs Mobile SDK - there is no PC version

Lisa Fedane
DJI Developer Support, US

Join DJI's Developer Community in our new Forum for Technical Discussions, Announcements and More:
https://forum.dji.com/forum-139-1.html?from=developer
