### ISSUE TITLE
error during initilaization

### ISSUE THREAD

**Issue by Aswath93** [dji-sdk/Onboard-SDK-ROS#40]
Hey,

I am at the activation step that needs to be done before using onboard-sdk-ros. I have modified the launch file "dji_sdk/launch/sdk_manifold.launch" accordingly.Now, When I try "roslaunch dji_sdk sdk_manifold.launch" I get the following error `ERROR _serialOpen,line 129: cannot open device /dev/ttyTHS1
ERROR init,line 44: ...fail to start serial
`
could anyone tell me what to do now?

edit:
I managed to find the right serial address and I get `STATUS init,line 46: ...succeed to start serial
[ INFO] [1468858894.814610464]: Succeed to create thread for readPoll
`

and its is stuck there, it is not going through with the activation.

Thanks

**Comment by lanyusea** [comment]
you serial port is not configured successfully.

It start read the port, but nothing received, then stuck here.

**Comment by Aswath93** [comment]
thanks for the reply,could you tell me how to configure it correctly?

**Comment by lanyusea** [comment]
connect your mobile with the RC, open DJI GO in your mobile.

**Comment by lanyusea** [comment]
r u using Manifold?

**Comment by Aswath93** [comment]
I did have my tablet connected to the paired rc with the dji go app open.
Anything else that I might be missing?

**Comment by Aswath93** [comment]
no i am trying to connect to my linux pc.

**Comment by lanyusea** [comment]
so, if you choose the correct serial port device, and open 'enable API' in DJI Assistant2

it may be your USB-TTL module doesn't work

**Comment by Aswath93** [comment]
I read on the dji developer forum that the signal voltage might be a problem. I am using the USB-TTL cable recommended by dji in the hardware guide. Is there another cable that you recommend?

**Comment by amenon7** [comment]
@Aswath93 : 

1.) Ensure serial device ID is the same as your launch file. 
2.) Ensure Enable API is set and you have the correct baud rate set. 
2.) Ensure RC is paired and DJI GO is running and connected to the internet. 
3.) Ensure RC is in F mode. OnboardSDK only works only in F mode. 

If you are using the recommended USB-TTL cable, you should not have a problem with your cable.

**Comment by Aswath93** [comment]
Hey Arjun,

Thank you for replying.

I did all those things.

I am finding the serial ID using "lsusb" command, and setting the permissions using "chmod" command.

I do not know what else to do!

Is there anything else I might have missed?

**Comment by amenonDJI** [comment]
@Aswath93 Have you tried this: To access the serial port, add your username to the dialout group by typing sudo usermod -a -G dialout $USER (you do not need to replace $USER with your username). Then logout and login again.
