### ISSUE TITLE
[HELP] Need IMU intrinsic details and IMU to Camera transformation

### ISSUE THREAD

**Issue by ShreyasManjunath** [dji-sdk/Onboard-SDK-ROS#408]
Hello DJI community,

I am currently working on DJI Matrice 210 v2 RTK drone equipped with Zenmuse X5S. I am unable to find relevant information about IMU noise and Tbc to be precise. Is there any documentation regarding the same? It will be of great help if you could provide intrinsic data and Tbc matrix.

Thank you in advance :)

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/40474'>Zendesk ticket #40474</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Do you need to obtain relevant parameters through OSDK? Currently OSDK cannot obtain IMU intrinsic details and Tbc matrix. OSDK can obtain related telemetry data through subscription function. You can refer to the website:
https://developer.dji.com/onboard-api-reference/group__telem.html

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
