### ISSUE TITLE
Stop gimbal from moving using ROS SDK

### ISSUE THREAD

**Issue by ShreyasManjunath** [dji-sdk/Onboard-SDK-ROS#412]
Hello Community,

I was trying to stop the gimbal movement and want to fix gimbal to an orientation. It seems even though i set gimbal orientation to a specified pose, the gimbal moves as I move and rotate the drone (Matrice 210v2 RTK). Is there anyway to stop or fix the gimbal at particular orientation. 

Thank you in advance.

Shreyas

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/40716'>Zendesk ticket #40716</a>:<br><br>Hi Shreyas,

Do you set the gimbal mode to Free mode? It can be set in DJI pilot. In Free mode, the gimbal won't rotate when rotate the drone.
