### ISSUE TITLE
[Need] xarco file or schematic of DJI Matrice 210 v2 RTK for calculation

### ISSUE THREAD

**Issue by ShreyasManjunath** [dji-sdk/Onboard-SDK-ROS#415]
Hello DJI Community,

I am in search of xarco file or schematic measurements of DJI Matrice 210 v2 RTK for calculating relative distances. Manually measuring it wouldn't make any sense to achieve precision in calculation. I hope some of you people would have generated schematic or have an official measurement document from DJI for this purpose.

Keep coding!

Thank you.

Shreyas

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/40914'>Zendesk ticket #40914</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Sorry, are you consulting the aircraft size chart of the M210 RTK v2 drone?
For aircraft information, you can download the aircraft user manual from the official DJI website（https://www.dji.com/hk-en/matrice-200-series-v2?site=brandsite&from=nav） or email to support@dji.com.

If you have questions about the use of the SDK, we suggest you to describe the SDK problem in detail and we will confirm it for you.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team
