### ISSUE TITLE
[Q] Downgrade the IMU publishing rate to 200 Hz

### ISSUE THREAD

**Issue by ShreyasManjunath** [dji-sdk/Onboard-SDK-ROS#425]
Hello Community,

Is there anyway to downgrade or down-sample IMU topic to 200 Hz or lower which is currently publishing at 400 Hz (On M210v2) ?

Thank you,

Shreyas

**Comment by dji-dev** [comment]
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/41675'>Zendesk ticket #41675</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

If you want to downgrade the frep of subscribe data from the FC, you can change the API Prams:freq
vehicle->subscribe->initPackageFromTopicList(packageID, numberOfTopics, topicList, sendTimeStamp, freq)

and about the ROS: dji_vehicle_node.cpp
initDataSubscribeFromFC
 ![](https://djisdksupport.zendesk.com/attachments/token/NpRokLihiueQDuZr17YgThCAS/?name=inline196896269.png)​

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/NpRokLihiueQDuZr17YgThCAS' target='zd_attach'>inline196896269.png</a>

**Comment by ShreyasManjunath** [comment]
Thank you :)
