### ISSUE TITLE
Waypoint mission behavior

### ISSUE THREAD

**Issue by gggoh1** [dji-sdk/Onboard-SDK-ROS#426]
I am using v4.0.1 of OSDK with M210 V2 RTK. I ran the sample mission_node waypoint mission, but it moves back a little bit when it reaches each waypoint.
Have anyone any idea about the cause of this?
<img width="917" alt=" 2020-12-04 9 51 36" src="https://user-images.githubusercontent.com/75458476/101109868-29e7b500-361b-11eb-9222-7445ddc96c17.png">

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/41721'>Zendesk ticket #41721</a>:<br><br>Hi. This is because there will be inertia when the drone reaches the waypoint.

**Comment by gggoh1** [comment]
@dji-dev thank you, I change idle_velocity

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/41721'>Zendesk ticket #41721</a>:<br><br>Yes. Setting a smaller idle_velocity can reduce overshoot.
