### ISSUE TITLE
Landing and attitude control

### ISSUE THREAD

**Issue by skyritsis** [dji-sdk/Onboard-SDK-ROS#44]
Hello,
While in landing, the drone responds to remote controller input, but does not seem to respond to attitude control commands issued via the onboard sdk. Should this be happening? If yes, is there a way to attitude control while landing?

Thank you in advance,
-SK

**Comment by lanyusea** [comment]
yes.

maybe you can create your own landing logic by the attitude control and disarm APIs.

**Comment by skyritsis** [comment]
Thank you. That's the way I'm doing it atm. I was just thinking if I should do it the other way around.
Thank you.
