### ISSUE TITLE
compatibility with Matrice 600

### ISSUE THREAD

**Issue by miguelolivaresmendez** [dji-sdk/Onboard-SDK-ROS#51]
I planing to buy a DJI Matrice 600 for research purpose, because I need more payload. I know that the onboard SDK is compatible with Matrice 600, what about the ROS version? is it compatible or is planned to be compatible? Is the manifold compatible with the Matrice 600? If so, me and my team will participate actively in this development.
Many thanks in advanced

**Comment by amenonDJI** [comment]
Yes the M600 does support the Onboard SDK pure Linux version and ROS versions. The manifold is also compatible with the M600. 

Please re-open the case if you have any other technical questions.

**Comment by gusmally** [comment]
Hi, will the Manifold 200 be compatible with the Manifold?
