### ISSUE TITLE
Time delay on Zenmuse Z3

### ISSUE THREAD

**Issue by cretaceous-creature** [dji-sdk/Onboard-SDK-ROS#62]
Hi, I am using DJI M100 with Zenmuse Z3 camera.
I wonder through the ROS packages provided by the Onboard_SDK_READ_CAM,
what is the time delay of the camera, 
since I use rviz to visualize it I can feel there maybe 0.5 seconds delay.
Are there any way to reduce the delay?

**Comment by amenonDJI** [comment]
@cretaceous-creature Could you please provide the link for "Onboard_SDK_READ_CAM"? Are you referring to the Manifold Cam library?

**Comment by amenonDJI** [comment]
@cretaceous-creature If you can continue to have an issue, please feel free to re-open.
