### ISSUE TITLE
Clarifying velocity control

### ISSUE THREAD

**Issue by Maksym-Samoilenko** [dji-sdk/Onboard-SDK-ROS#77]
Hello,
Is there a possibility to control velocity during perfoming global_position_navigation_send_request?
It means, velocity of M100 is 20 m/s by default during global navigation(it's too quick for testing purposes).
I've tried something that:
        drone.takeoff()
	time.sleep(3)
	drone.global_position_navigation_send_request(globlat1, globlon1, 5)
	for i in range(500):
	drone.velocity_control(DJIDrone.HORIZ_POS|DJIDrone.VERT_VEL|DJIDrone.YAW_ANG|DJIDrone.HORIZ_BODY|DJIDrone.STABLE_ON, 5, 5, 5, 10)
		time.sleep(0.02)
#During 0.02*500 sec. Horizontal&Vertical speed are supposed to be limited by 5 m/s
	drone.landing()

But it works incorrectly in simulator(strange trajectories in flight).
Is there a way to reduce speed?
Thanks,
Best Regards

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
