### ISSUE TITLE
Telemetry Widget

### ISSUE THREAD

**Issue by AldrichCabrera** [dji-sdk/Onboard-SDK-ROS#83]
Hi!

Anyone know about telemetry widgets in ROS? I would like to visualize the telemetry of a Matrice 100 in a widget that can subscribe to the position, altitude and angles of the matrice.Only it shows a kind of virtual horizon.

Thanks,

**Comment by amenonDJI** [comment]
@AldrichCabrera You can use the existing ROS feature to subscribe multiple Topics and visualize data. There isn't a preexisting Widget to do this. 

If you happen to have any other questions, please feel free to open a new issue.
