### ISSUE TITLE
Change Max Speed in Waypoint Control

### ISSUE THREAD

**Issue by suarez-ramon** [dji-sdk/Onboard-SDK-ROS#87]
When sending gps waypoint lists the velocity from one point to the other is very big which means abrupt movement of the drone. Is there a config file or a way to change the max speed to make this movement less abrupt?

Thanks!

**Comment by amenonDJI** [comment]
@suarez-ramon Which version of Onboard SDK, aircraft and platform are you using? 

The Waypoint Initialization allows for a "Max Velocity" parameter before you upload any of the GPS points. If you're using Onboard SDK 3.3 - take a look at the linux samples - mission_sample.cpp 
``
void
setWaypointInitDefaults(WayPointInitSettings* fdata)
``
This function initializes the max velocity parameter you're interested in.

**Comment by amenonDJI** [comment]
@suarez-ramon Closed due to inactivity. Please re-open if you continue to face any issues.
