### ISSUE TITLE
Waypoint Mission Time

### ISSUE THREAD

**Issue by GitPlz** [dji-sdk/Onboard-SDK-ROS#88]
Uploading a waypoint mission takes a minimum of 2 seconds per waypoint because sleep(2) is called after each waypoint is uploaded. This doesn't scale, as it takes over 3 minutes to upload 99 waypoints. Why is there a need to sleep for 2 seconds between waypoints, and what can be done to remove this limitation?

The sleeping happens in DJISDKMission::mission_wp_upload_callback method.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
