### ISSUE TITLE
Waypoint Upload > 30 points fails

### ISSUE THREAD

**Issue by GitPlz** [dji-sdk/Onboard-SDK-ROS#89]
Using the sample code, if you change the number of waypoints to 30, the last waypoint uploaded returns an error 0xE1 Invalid waypoint point data. 

Alternatively, using the sample code, as-is, if you run "rosrun dji_sdk_demo dji_sdk_client", and make the selection for a waypoint mission upload (22) 8 times, you will get the same error 0xE1 Invalid waypoint point data.

**Comment by dji-kyle** [comment]
Please update to OSDK 3.9 and OSDK-ROS 3.8, the following forum community is recommanded for you, if the problem persists, or new questions about the DJI SDK,
https://djisdksupport.zendesk.com/hc/en-us/community/topics
