### ISSUE TITLE
GPS altitude not correct

### ISSUE THREAD

**Issue by acdriec** [dji-sdk/Onboard-SDK-ROS#9]
I tried waypointnavigation. 
In simulation everything worked fine, also in real life everything went fine, except the GPS altitude () was not correct (-137m in Belgium ?!). Although the matrice went to the correct GPS coordinate and altitude (is guess it used baro altitude ?). But the waypoint altitude and altitude-progress (waypoint_navigation_feedback.altitude_progress) was not correct. Any idea what could be wrong ?

**Comment by lanyusea** [comment]
You can select the way of calculating altitude in N1 Assistant. fused or raw.

Could you specify what the "be wrong" is.
If you mean it cannot reach 100% and keeps being 99% or whatever, you can increase the threshold in action.cpp file. It should solve it.

**Comment by acdriec** [comment]
Well, latitude and longitude are correct, but altitude is not correct (in the message). It says that I am at - 137m and the waypoint progress of altitude stays at around 7%. Although the matrice goes to the correct altitude. 

Thank you for you reply!

**Comment by lanyusea** [comment]
em... that's quite interesting.

Could you use `ros echo` to check the values of `height` and `altitude` in global_position topic, together with its `health flag`?

**Comment by acdriec** [comment]
I will test this on monday,

Thank you

**Comment by lanyusea** [comment]
@acdriec  how is everything now?

**Comment by acdriec** [comment]
I will try it today (on an other location). Sorry for the delay !

**Comment by lanyusea** [comment]
@acdriec  no rush. I'm just wondering if everything goes well or there is really some hiding bugs in our program. ;)

**Comment by acdriec** [comment]
Healt was 4 today and height was correct. But we tested at an other location. I let you know if it happens again. Thanks!
