### ISSUE TITLE
Lightbridge2 on ros

### ISSUE THREAD

**Issue by albert21martins** [dji-sdk/Onboard-SDK-ROS#94]
Is is possible to see every channel of the LB2 on a ROS topic??

thanks for the help

**Comment by rohitsantdji** [comment]
On OSDK 3.3, you can now receive all six channels (roll, pitch, yaw, throttle, gear, mode) on a topic. See the updated [wiki](http://wiki.ros.org/dji_sdk) for full documentation.

**Comment by albert21martins** [comment]
Yes that was already in the older OSDK.
What is actually buttons used for in the topic (dji_sdk/rc)
      s << indent << "  buttons[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.buttons[i]);

I mean I would like to avoid an extra controller in order to read the PWM signals from the MFIO as I am already buying the LB2 Extension kit. It would be really usefull if we could access to the Extensions buttons from the API.

**Comment by rohitsantdji** [comment]
Got it - this feature has not been planned yet, though it's possible a future firmware might expose this to the OSDK.

Can you expand a little more on the PWM reading use case? Could you perhaps use the OSDK<->MSDK communication link to read this data?

**Comment by albert21martins** [comment]
Our Payload needs SPPM signal to work. Therefore I wanted to read directly from the API the pwm values from MFIO and generate a SPPM signal.  I will have to use an extra MCU in order to read the PWM because the actual companion PC has no free pins for this purpose.  Unless you can provide me a better solution.

**Comment by amenonDJI** [comment]
@albert21martins Buttons is a part of Joy topic that we use for RC and is unused. Please reopen if you have any other issues.
